<?php
declare(strict_types=1);

namespace App\Services\LegacyAppointment;

use PDO;
use RuntimeException;
use Throwable;

final class LegacyArpaAppointmentMigrationService
{
    private const WORKFLOW=[
        'asc_varify_by'=>['VERIFY','ASC','ASC_VERIFIED'],
        'asc_approve_by'=>['APPROVE','ASC','ASC_APPROVED'],
        'district_varify_by'=>['VERIFY','DISTRICT','DISTRICT_VERIFIED'],
        'district_approve_by'=>['APPROVE','DISTRICT','DISTRICT_APPROVED'],
        'national_varify_by'=>['VERIFY','NATIONAL','NATIONAL_VERIFIED'],
        'national_approve_by'=>['APPROVE','NATIONAL','NATIONAL_APPROVED'],
    ];
    private const REASONS=['1'=>'TRANSFER','2'=>'RETIREMENT','3'=>'DEATH','4'=>'RELEASE_FROM_SERVICE','5'=>'VACATION_OF_POST','6'=>'RESIGNATION','7'=>'TERMINATION_OF_APPOINTMENT','8'=>'SUSPENSION_FROM_WORK','9'=>'LEAVE_PREPARATORY_TO_RETIREMENT','10'=>'MATERNITY_LEAVE','11'=>'ACCIDENT_LEAVE','12'=>'ACADEMIC_LEAVE','13'=>'FOREIGN_LEAVE_WITHOUT_PAY','14'=>'COMPULSORY_LEAVE','15'=>'SPECIAL_SICK_LEAVE','16'=>'MEDICAL_LEAVE'];

    public function __construct(private readonly PDO $target,private readonly int $batchSize=100){}

    public function dryRun():array{return $this->analyse();}

    public function execute():array
    {
        $report=$this->analyse();
        $runId=(string)$this->target->query('SELECT UUID()')->fetchColumn();$this->target->prepare("INSERT INTO legacy_arpa_appointment_migration_run(id,mode,status,reconciled_records,warning_count,blocker_count,summary_json,report_path) VALUES(?,'EXECUTE','RUNNING',?,?,?,?,?)")->execute([$runId,$report['total']['reconciled_business_records'],$report['warnings'],$report['true_execution_blockers'],$this->json($report['summary']),$report['report_path']]);
        $counts=['business'=>0,'requests'=>0,'operational'=>0,'workflow'=>0,'references'=>0,'skipped_manual_review'=>0,'record_failures'=>0];
        try{
            foreach($report['records'] as $record){
                if($record['migration_classification']==='MANUAL_REVIEW_REQUIRED'){
                    $counts['skipped_manual_review']++;
                    $this->target->prepare("INSERT INTO legacy_arpa_appointment_migration_issue(migration_run_id,reconciled_business_key,issue_type,severity,message,evidence_json) VALUES(?,?,'MANUAL_REVIEW_SKIPPED','BLOCKER',?,?)")->execute([$runId,$record['reconciled_business_key'],'Record was preserved for human review and was not imported.',$this->json(['reasons'=>$record['manual_review_reasons'],'baseline_classification'=>$record['baseline_classification'],'evidence_class'=>$record['special_evidence_class']??$record['location_confidence'],'source_references'=>$record['source_references_json']])]);
                    continue;
                }
                if(!$record['would_create_business_record'])continue;
                try{
                    $this->target->beginTransaction();$created=$this->insertRecord($record);$this->target->commit();foreach(['business','requests','operational','workflow','references'] as $key)$counts[$key]+=$created[$key];
                }catch(Throwable $e){
                    if($this->target->inTransaction())$this->target->rollBack();$counts['record_failures']++;
                    $this->target->prepare("INSERT INTO legacy_arpa_appointment_migration_issue(migration_run_id,reconciled_business_key,issue_type,severity,message,evidence_json) VALUES(?,?,'RECORD_IMPORT_FAILED','BLOCKER',?,?)")->execute([$runId,$record['reconciled_business_key'],'Record-isolated import failed; unrelated records continued.',$this->json(['error_category'=>get_class($e),'migration_classification'=>$record['migration_classification']])]);
                }
            }
            $status=($report['warnings']||$report['true_execution_blockers']||$counts['record_failures'])?'COMPLETED_WITH_WARNINGS':'COMPLETED';$this->target->prepare("UPDATE legacy_arpa_appointment_migration_run SET status=?,business_records_created=?,requests_created=?,operational_records_created=?,workflow_actions_created=?,source_references_created=?,completed_at=NOW() WHERE id=?")->execute([$status,$counts['business'],$counts['requests'],$counts['operational'],$counts['workflow'],$counts['references'],$runId]);return ['run_id'=>$runId,'counts'=>$counts,'report'=>$report];
        }catch(Throwable $fatal){
            if($this->target->inTransaction())$this->target->rollBack();
            $statement=$this->target->prepare("UPDATE legacy_arpa_appointment_migration_run SET status='FAILED',business_records_created=?,requests_created=?,operational_records_created=?,workflow_actions_created=?,source_references_created=?,completed_at=NOW(),error_message=? WHERE id=?");
            $statement->execute([$counts['business'],$counts['requests'],$counts['operational'],$counts['workflow'],$counts['references'],'Migration infrastructure failure: '.get_class($fatal),$runId]);
            throw $fatal;
        }
    }

    private function analyse():array
    {
        $rows=$this->target->query("SELECT p.*,o.dad_number officer_dad_number,o.name_with_initials officer_name,COALESCE(ar.name_en,par.name_en) resolved_arpa_name,si.candidate_asc_id special_candidate_asc,si.source_confidence special_evidence_class,si.candidate_evidence_json special_candidate_evidence_json,CASE WHEN si.candidate_asc_id IS NULL THEN 0 ELSE 1 END special_candidate_count,sr.resolution_status special_resolution,sr.selected_target_asc_id special_asc,sr.activation_decision special_activation,mr.resolution_status missing_resolution,mr.selected_target_asc_id missing_asc,mr.selected_target_arpa_id missing_arpa,cr.resolution_status conflict_resolution,cr.activation_decision conflict_activation FROM legacy_arpa_appointment_preview p JOIN officer o ON o.id=p.officer_id LEFT JOIN location ar ON ar.id=p.arpa_location_id LEFT JOIN location par ON par.id=JSON_UNQUOTE(JSON_EXTRACT(p.location_provenance_json,'$.target_context_id')) LEFT JOIN legacy_arpa_reconciliation_item si ON si.reconciled_business_key=p.reconciled_business_key AND si.item_type='SPECIAL_ASC' AND si.active=1 LEFT JOIN legacy_arpa_appointment_resolution sr ON sr.reconciliation_item_id=si.id LEFT JOIN legacy_arpa_reconciliation_item mi ON mi.reconciled_business_key=p.reconciled_business_key AND mi.item_type='MISSING_ARPA_LOCATION' AND mi.active=1 LEFT JOIN legacy_arpa_appointment_resolution mr ON mr.reconciliation_item_id=mi.id LEFT JOIN legacy_arpa_reconciliation_item ci ON ci.reconciled_business_key=p.reconciled_business_key AND ci.item_type='CURRENT_CONFLICT' AND ci.active=1 LEFT JOIN legacy_arpa_appointment_resolution cr ON cr.reconciliation_item_id=ci.id WHERE p.active=1 ORDER BY p.reconciled_business_key")->fetchAll();
        $existing=[];foreach($this->target->query("SELECT reconciled_business_key FROM legacy_arpa_appointment_business_record WHERE source_system='dems_legacy_hr'")->fetchAll(PDO::FETCH_COLUMN) as $key)$existing[(string)$key]=true;
        $office=[];foreach($this->target->query("SELECT oa.officer_id,o.linked_location_id asc_id,oa.effective_from,oa.effective_to FROM officer_office_assignment oa JOIN office o ON o.id=oa.office_id JOIN office_type ot ON ot.id=o.office_type_id AND ot.system_key='ASC_OFFICE' WHERE oa.active=1 AND oa.approval_status='APPROVED' AND o.operational_status='ACTIVE' AND o.approval_status='APPROVED'")->fetchAll() as $r)$office[$r['officer_id'].'|'.$r['asc_id']][]=$r;
        $summary=['policy'=>['baseline_date'=>LegacyArpaMigrationPolicy::BASELINE_DATE,'manual_decision_required_for_deterministic_evidence'=>0,'record_isolated_execution'=>1,'legacy_letters_generated'=>0],'total'=>['reconciled_business_records'=>count($rows),'eligible_migration_records'=>0,'request_history_only_records'=>0,'operational_records'=>0,'current_operational_candidates'=>0,'ended_historical_records'=>0],'baseline_periods'=>array_fill_keys(['PRE_BASELINE_CARRIED_FORWARD','LEGACY_PERIOD','PRE_BASELINE_HISTORY','DATE_REVIEW_REQUIRED'],0),'migration_classification'=>array_fill_keys(['MIGRATABLE_OPERATIONAL','MIGRATABLE_HISTORY','MIGRATABLE_HISTORICAL_EXCEPTION','MANUAL_REVIEW_REQUIRED'],0),'special_resolution'=>['automatically_resolvable'=>0,'human_confirmed'=>0,'no_candidate_preserved'=>0,'ambiguous_manual_review'=>0,'strong_derived_automatic'=>0,'current_state_only_automatic'=>0],'arpa_division'=>array_fill_keys(['PERMANENT','ACTING','DUTY_COVERING','ATTEND_TO_DUTY'],0),'subject_function'=>array_fill_keys(['AGRARIAN_BANK','SALES_SHOP','SITHAMU'],0),'workflow'=>array_fill_keys(['asc_verified','asc_approved','district_verified','district_approved','national_verified','national_approved','actor_mappings_resolved','actor_mappings_unresolved','unavailable_timestamps'],0),'current_activation'=>['valid_current_operational_records'=>0,'scheduled_operational_records'=>0,'preserved_non_operational'=>0,'blocked_business_rule'=>0,'blocked_office_assignment'=>0,'blocked_unresolved_asc'=>0,'blocked_missing_arpa_division'=>0,'blocked_other'=>0],'history'=>['ended_records'=>0,'projected_ended_operational_records'=>0,'historical_rule_exception_records'=>0,'business_rule_exceptions_preserved'=>0,'end_date_without_reason'=>0,'reason_without_end_date'=>0],'reconciliation'=>['unresolved_migration_workbench_decisions'=>0,'deterministic_without_manual_decision'=>0,'exact_duplicates'=>0,'continuation_matches'=>0,'source_references_expected'=>0,'existing_already_migrated'=>0,'would_update'=>0],'target_projection'=>['business_records_to_create'=>0,'appointment_requests_to_create'=>0,'division_requests_to_create'=>0,'subject_requests_to_create'=>0,'operational_arpa_appointments_to_create'=>0,'subject_assignment_records_to_create'=>0,'sithamu_subdesignation_periods_to_create'=>0,'workflow_events_to_create'=>0,'source_references_to_create'=>0,'historical_only_unmigrated_records_remaining'=>0,'projected_open_appointments'=>0,'projected_historical_appointments'=>0,'projected_scheduled_appointments'=>0],'profile_example'=>[]];
        $issues=[];$projected=[];
        foreach($rows as $row){$row=$this->decode($row);$special=$row['assignment_category']==='ASC_FUNCTION';$candidateEvidence=json_decode((string)($row['special_candidate_evidence_json']??''),true)?:[];if(str_contains(strtolower((string)($candidateEvidence['method']??'')),'multiple'))$row['special_candidate_count']=2;$specialState=$special?LegacyArpaMigrationPolicy::specialResolutionState($row):null;$specialPreserved=$special&&$row['special_resolution']==='CONFIRMED'&&$row['special_activation']==='PRESERVE_HISTORY_ONLY';$asc=$special?LegacyArpaMigrationPolicy::deterministicAsc($row):($row['missing_resolution']==='CONFIRMED'&&$row['missing_asc']?$row['missing_asc']:$row['asc_location_id']);$provenanceArpa=in_array($row['location_confidence'],['EXACT','STRONG_DERIVED'],true)?($row['location_provenance_json']['target_context_id']??null):null;$arpa=$special?null:($row['missing_resolution']==='CONFIRMED'&&$row['missing_arpa']?$row['missing_arpa']:($row['arpa_location_id']?:$provenanceArpa));$row['resolved_asc_id']=$asc;$row['resolved_arpa_id']=$arpa;$row['baseline_date']=LegacyArpaMigrationPolicy::BASELINE_DATE;$row['baseline_classification']=LegacyArpaMigrationPolicy::periodClassification($row['effective_from'],$row['effective_to']);$row['carried_into_baseline']=LegacyArpaMigrationPolicy::carriedIntoBaseline($row['effective_from'],$row['effective_to']);
            $summary['baseline_periods'][$row['baseline_classification']??'DATE_REVIEW_REQUIRED']++;if($special)$summary['subject_function'][$row['subject_kind']]++;else $summary['arpa_division'][$row['appointment_type']]++;if($row['effective_to']){$summary['total']['ended_historical_records']++;$summary['history']['ended_records']++;}if($row['historical_exception'])$summary['history']['historical_rule_exception_records']++;if($row['effective_to']&&!$row['legacy_reason_id'])$summary['history']['end_date_without_reason']++;if(!$row['effective_to']&&$row['legacy_reason_id'])$summary['history']['reason_without_end_date']++;
            $summary['reconciliation']['source_references_expected']+=count($row['source_references_json']);if($row['reconciliation_class']==='EXACT_DUPLICATE')$summary['reconciliation']['exact_duplicates']++;if($row['reconciliation_class']==='SAME_APPOINTMENT_CONTINUATION')$summary['reconciliation']['continuation_matches']++;
            foreach(self::WORKFLOW as $field=>$definition){$actor=$row['workflow_json'][$field]??null;if(!empty($actor['legacy_user_id'])){if(!empty($actor['target_user']['id'])){$summary['workflow'][str_replace('_by','',str_replace('varify','verified',str_replace('approve','approved',$field)))]++;$summary['workflow']['actor_mappings_resolved']++;$summary['workflow']['unavailable_timestamps']++;}else $summary['workflow']['actor_mappings_unresolved']++;}}
            $today=date('Y-m-d');$open=$row['effective_to']===null;$invalidDateRange=$row['effective_from']!==null&&$row['effective_to']!==null&&$row['effective_to']<$row['effective_from'];if($invalidDateRange){$row['historical_exception_types_json'][]='INVALID_DATE_RANGE';$row['historical_exception_types_json']=array_values(array_unique($row['historical_exception_types_json']));$row['historical_exception']=true;}$current=$open&&$row['effective_from']!==null&&$row['effective_from']<=$today;$scheduled=$open&&$row['effective_from']!==null&&$row['effective_from']>$today;if($current)$summary['total']['current_operational_candidates']++;
            $manualReasons=[];if($row['effective_from']===null)$manualReasons[]='MISSING_EFFECTIVE_FROM';if(!$special&&(!$asc||!$arpa))$manualReasons[]='IMPOSSIBLE_ARPA_LOCATION_IDENTITY';if($special&&$specialState==='AMBIGUOUS')$manualReasons[]='AMBIGUOUS_ASC_IDENTITY';
            $blockReason=$invalidDateRange?'INVALID_DATE_RANGE':null;$activationValid=(bool)$row['legacy_operational_approval']&&!$specialPreserved&&!$invalidDateRange&&$manualReasons===[];
            if($special&&$specialState==='NO_CANDIDATE'){$activationValid=false;$blockReason='UNRESOLVED_ASC';}
            if($open&&$row['current_conflict']&&!(($row['conflict_resolution']??null)==='CONFIRMED'&&($row['conflict_activation']??null)==='ACTIVATE_CURRENT')){$activationValid=false;$blockReason='BUSINESS_RULE';}
            if(($current||$scheduled)&&$activationValid){$scopeDate=$scheduled?$row['effective_from']:$today;if(!$this->officeCovers($office,$row['officer_id'],$asc,$scopeDate)){$activationValid=false;$blockReason='MISSING_CURRENT_ASC_OFFICE';}}
            if(!$row['legacy_operational_approval']&&$blockReason===null)$blockReason='INCOMPLETE_LEGACY_WORKFLOW';
            if($manualReasons!==[])$migrationClass='MANUAL_REVIEW_REQUIRED';elseif($specialState==='NO_CANDIDATE'||$specialPreserved||($open&&$blockReason!==null)||$row['historical_exception']||$row['current_conflict'])$migrationClass='MIGRATABLE_HISTORICAL_EXCEPTION';elseif($row['effective_to']!==null||!$row['legacy_operational_approval'])$migrationClass='MIGRATABLE_HISTORY';else $migrationClass='MIGRATABLE_OPERATIONAL';
            $exceptionCodes=array_values(array_unique(array_merge($row['historical_exception_types_json'],$row['current_conflict_types_json'],array_filter([$migrationClass==='MIGRATABLE_HISTORICAL_EXCEPTION'?$blockReason:null,$specialState==='NO_CANDIDATE'?'UNRESOLVED_ASC_PRESERVED':null]))));$row['historical_exception_types_json']=$exceptionCodes;$row['historical_exception']=$exceptionCodes!==[];
            $operational=(bool)$row['legacy_operational_approval']&&!$invalidDateRange&&$manualReasons===[]&&$asc!==null&&($special||$arpa!==null)&&($row['effective_to']!==null||$activationValid);$historyOnly=$migrationClass==='MIGRATABLE_HISTORICAL_EXCEPTION'||$row['effective_to']!==null||$specialPreserved;
            if($special){$evidenceRow=$row;$evidenceRow['special_resolution']=null;$evidenceRow['special_asc']=null;$candidateDeterministic=LegacyArpaMigrationPolicy::deterministicAsc($evidenceRow)!==null;if($candidateDeterministic){$summary['special_resolution']['automatically_resolvable']++;$evidence=strtolower((string)$row['special_evidence_class']);if($evidence==='strong_derived')$summary['special_resolution']['strong_derived_automatic']++;if($evidence==='current_state_only')$summary['special_resolution']['current_state_only_automatic']++;}if($specialState==='HUMAN_CONFIRMED')$summary['special_resolution']['human_confirmed']++;elseif($specialState==='DETERMINISTIC')$summary['reconciliation']['deterministic_without_manual_decision']++;elseif($specialState==='NO_CANDIDATE')$summary['special_resolution']['no_candidate_preserved']++;else $summary['special_resolution']['ambiguous_manual_review']++;}
            $summary['migration_classification'][$migrationClass]++;if($migrationClass!=='MANUAL_REVIEW_REQUIRED')$summary['total']['eligible_migration_records']++;else{foreach($manualReasons as $reason)$issues[$row['reconciled_business_key']][]=$reason;$summary['reconciliation']['unresolved_migration_workbench_decisions']++;}
            if($operational){$summary['total']['operational_records']++;if($row['effective_to']){$summary['history']['projected_ended_operational_records']++;$summary['target_projection']['projected_historical_appointments']++;}elseif($scheduled){$summary['current_activation']['scheduled_operational_records']++;$summary['target_projection']['projected_scheduled_appointments']++;}elseif(!$historyOnly){$summary['current_activation']['valid_current_operational_records']++;$summary['target_projection']['projected_open_appointments']++;}}
            else{$summary['total']['request_history_only_records']++;$summary['target_projection']['historical_only_unmigrated_records_remaining']++;if($migrationClass==='MIGRATABLE_HISTORICAL_EXCEPTION')$summary['current_activation']['preserved_non_operational']++;}
            if($migrationClass==='MIGRATABLE_HISTORICAL_EXCEPTION')$summary['history']['business_rule_exceptions_preserved']++;
            if($open&&$blockReason){$key=match($blockReason){'BUSINESS_RULE'=>'blocked_business_rule','MISSING_CURRENT_ASC_OFFICE'=>'blocked_office_assignment','UNRESOLVED_ASC'=>'blocked_unresolved_asc',default=>'blocked_other'};$summary['current_activation'][$key]++;}
            $wouldCreate=!isset($existing[$row['reconciled_business_key']])&&$migrationClass!=='MANUAL_REVIEW_REQUIRED';if(isset($existing[$row['reconciled_business_key']]))$summary['reconciliation']['existing_already_migrated']++;if($wouldCreate){$summary['target_projection']['business_records_to_create']++;$summary['target_projection']['appointment_requests_to_create']++;$summary['target_projection'][$special?'subject_requests_to_create':'division_requests_to_create']++;$summary['target_projection']['workflow_events_to_create']+=$this->workflowCount($row);$summary['target_projection']['source_references_to_create']+=count($row['source_references_json']);if($operational){if($special){$summary['target_projection']['subject_assignment_records_to_create']++;if($row['subject_kind']==='SITHAMU')$summary['target_projection']['sithamu_subdesignation_periods_to_create']++;}else $summary['target_projection']['operational_arpa_appointments_to_create']++;}}
            $row['migration_classification']=$migrationClass;$row['operational_projection']=$operational;$row['legacy_history_only']=$historyOnly;$row['activation_block_reason']=$blockReason;$row['manual_review_reasons']=$manualReasons;$row['would_create_business_record']=$wouldCreate;$projected[]=$row;
        }
        $summary['true_execution_blockers']=$summary['migration_classification']['MANUAL_REVIEW_REQUIRED'];$summary['warnings']=$summary['history']['business_rule_exceptions_preserved']+$summary['history']['end_date_without_reason']+$summary['history']['reason_without_end_date'];$summary['profile_example']=$this->profileExample($projected);
        $path=$this->writeReport($summary,$projected,$issues);return $summary+['summary'=>$summary,'records'=>$projected,'issues'=>$issues,'report_path'=>$path];
    }

    private function insertRecord(array $r):array
    {
        $businessId=$this->uuid();$requestId=$this->uuid();$special=$r['assignment_category']==='ASC_FUNCTION';$targetConcept=$special?$r['subject_kind'].'_SUBJECT':'ARPA_DIVISION_APPOINTMENT';$snapshot=$this->json($r);
        $this->target->prepare("INSERT INTO legacy_arpa_appointment_business_record(id,reconciled_business_key,reconciliation_class,target_concept,officer_id,source_snapshot_json) VALUES(?,?,?,?,?,?)")->execute([$businessId,$r['reconciled_business_key'],$r['reconciliation_class'],$targetConcept,$r['officer_id'],$snapshot]);
        $workflow=$this->targetWorkflowState($r['workflow_state']);$exceptions=$this->json($r['historical_exception_types_json']);$origin=$this->json(['source_system'=>'dems_legacy_hr','reconciled_business_key'=>$r['reconciled_business_key'],'source_references'=>$r['source_references_json'],'location_provenance'=>$r['location_provenance_json'],'baseline_date'=>$r['baseline_date'],'baseline_classification'=>$r['baseline_classification'],'carried_into_baseline'=>$r['carried_into_baseline'],'migration_classification'=>$r['migration_classification'],'evidence_class'=>$r['special_evidence_class']??$r['location_confidence'],'legacy_letter_policy'=>'NO_NEW_LETTER_GENERATED']);
        if($special){$subject=$this->subject((string)$r['subject_kind']);$this->target->prepare("INSERT INTO arpa_subject_assignment_request(id,record_origin,request_type,officer_id,asc_location_id,subject_id,requested_effective_from,requested_effective_to,request_remarks,location_snapshot_json,workflow_status,legacy_history_only,legacy_exception,legacy_exception_codes_json,created_by,origin_metadata_json) VALUES(?,'LEGACY_IMPORT','ASSIGN',?,?,?,?,?,?,?,?,?,?,?,NULL,?)")->execute([$requestId,$r['officer_id'],$r['resolved_asc_id'],$subject['id'],$r['effective_from'],$r['effective_to'],'Imported reconciled legacy history',$this->json($r['location_provenance_json']),$workflow,$r['legacy_history_only']?1:0,$r['historical_exception']?1:0,$exceptions,$origin]);}
        else{$this->target->prepare("INSERT INTO arpa_division_appointment_request(id,record_origin,request_type,officer_id,appointment_type,asc_location_id,arpa_division_location_id,requested_effective_from,requested_effective_to,request_remarks,location_snapshot_json,workflow_status,legacy_history_only,legacy_exception,legacy_exception_codes_json,created_by,origin_metadata_json) VALUES(?,'LEGACY_IMPORT','APPOINTMENT',?,?,?,?,?,?,?,?,?,?,?, ?,NULL,?)")->execute([$requestId,$r['officer_id'],$r['appointment_type'],$r['resolved_asc_id'],$r['resolved_arpa_id'],$r['effective_from'],$r['effective_to'],'Imported reconciled legacy history',$this->json($r['location_provenance_json']),$workflow,$r['legacy_history_only']?1:0,$r['historical_exception']?1:0,$exceptions,$origin]);}
        $workflowCount=$this->insertWorkflow($special?'arpa_subject_workflow_action':'arpa_appointment_workflow_action',$requestId,$r['workflow_json']);$operationalId=null;$subPeriodId=null;$closureId=null;
        if($r['operational_projection']){if($special){[$operationalId,$subPeriodId,$closureId]=$this->insertSubjectOperational($requestId,$r,$origin);}else[$operationalId,$closureId]=$this->insertDivisionOperational($requestId,$r,$origin);}
        $refs=0;foreach($r['source_references_json'] as $reference){[$table,$legacyId]=explode(':',$reference,2);$this->target->prepare("INSERT INTO legacy_arpa_appointment_source_reference(business_record_id,source_table,legacy_appointment_id,target_appointment_request_id,target_appointment_id,target_subject_request_id,target_subject_assignment_id,target_sub_designation_period_id,legacy_payload_json) VALUES(?,?,?,?,?,?,?,?,?)")->execute([$businessId,$table,$legacyId,$special?null:$requestId,$special?null:$operationalId,$special?$requestId:null,$special?$operationalId:null,$subPeriodId,$snapshot]);$refs++;}
        return ['business'=>1,'requests'=>1,'operational'=>$operationalId?1:0,'workflow'=>$workflowCount,'references'=>$refs];
    }

    private function insertDivisionOperational(string $requestId,array $r,string $origin):array
    {
        $id=$this->uuid();$loc=$this->locations([$r['province_location_id'],$r['district_location_id'],$r['resolved_asc_id'],$r['resolved_arpa_id']]);$province=$loc[$r['province_location_id']]??[];$district=$loc[$r['district_location_id']]??[];$asc=$loc[$r['resolved_asc_id']]??[];$arpa=$loc[$r['resolved_arpa_id']]??[];
        $sql="INSERT INTO arpa_division_appointment(id,record_origin,request_id,officer_id,appointment_type,service_permanency_snapshot,service_permanency_source,province_location_id_snapshot,district_location_id_snapshot,asc_location_id,arpa_division_location_id,province_dad_snapshot,province_name_snapshot,district_dad_snapshot,district_name_snapshot,asc_dad_snapshot,asc_name_snapshot,arpa_dad_snapshot,arpa_name_snapshot,hierarchy_snapshot_json,effective_from,legacy_history_only,legacy_exception,legacy_exception_codes_json,approved_by,approved_at,approval_timestamp_provenance,origin_metadata_json) VALUES(:id,'LEGACY_IMPORT',:request_id,:officer_id,:appointment_type,:permanency,:permanency_source,:province_id,:district_id,:asc_id,:arpa_id,:province_dad,:province_name,:district_dad,:district_name,:asc_dad,:asc_name,:arpa_dad,:arpa_name,:hierarchy,:effective_from,:history_only,:legacy_exception,:exception_codes,NULL,NULL,'UNAVAILABLE_FROM_LEGACY_SOURCE',:origin)";
        $params=['id'=>$id,'request_id'=>$requestId,'officer_id'=>$r['officer_id'],'appointment_type'=>$r['appointment_type'],'permanency'=>$r['service_permanency_snapshot'],'permanency_source'=>$r['service_permanency_source'],'province_id'=>$r['province_location_id'],'district_id'=>$r['district_location_id'],'asc_id'=>$r['resolved_asc_id'],'arpa_id'=>$r['resolved_arpa_id'],'province_dad'=>$province['dad_number']??null,'province_name'=>$province['name_en']??null,'district_dad'=>$district['dad_number']??null,'district_name'=>$district['name_en']??null,'asc_dad'=>$asc['dad_number'],'asc_name'=>$asc['name_en'],'arpa_dad'=>$arpa['dad_number'],'arpa_name'=>$arpa['name_en'],'hierarchy'=>$this->json($r['location_provenance_json']),'effective_from'=>$r['effective_from'],'history_only'=>$r['legacy_history_only']?1:0,'legacy_exception'=>$r['historical_exception']?1:0,'exception_codes'=>$this->json($r['historical_exception_types_json']),'origin'=>$origin];
        try{$this->target->prepare($sql)->execute($params);}catch(Throwable $e){throw new RuntimeException($e->getMessage().' [columns=28, values=28, parameters='.count($params).']',0,$e);}$closure=null;if($r['effective_to']){$closure=$this->uuid();$reason=$this->reason($r['legacy_reason_id']);$this->target->prepare("INSERT INTO arpa_division_appointment_closure(id,record_origin,appointment_id,request_id,effective_to,end_reason_id,legacy_reason_id,legacy_reason_text,closure_kind,remarks,context_snapshot_json,approved_by,approved_at,approval_timestamp_provenance,origin_metadata_json) VALUES(:id,'LEGACY_IMPORT',:appointment_id,:request_id,:effective_to,:reason_id,:legacy_reason_id,:legacy_reason_text,'DIRECT','Imported reconciled legacy closure',:snapshot,NULL,NULL,'UNAVAILABLE_FROM_LEGACY_SOURCE',:origin)")->execute(['id'=>$closure,'appointment_id'=>$id,'request_id'=>$requestId,'effective_to'=>$r['effective_to'],'reason_id'=>$reason,'legacy_reason_id'=>$r['legacy_reason_id'],'legacy_reason_text'=>$r['legacy_reason_text'],'snapshot'=>$this->json($r['location_provenance_json']),'origin'=>$origin]);}return [$id,$closure];
    }
    private function insertSubjectOperational(string $requestId,array $r,string $origin):array
    {
        $id=$this->uuid();$subject=$this->subject($r['subject_kind']);$loc=$this->locations([$r['province_location_id'],$r['district_location_id'],$r['resolved_asc_id']]);$province=$loc[$r['province_location_id']]??[];$district=$loc[$r['district_location_id']]??[];$asc=$loc[$r['resolved_asc_id']]??[];$exclusive=in_array($r['subject_kind'],['AGRARIAN_BANK','SALES_SHOP','SITHAMU'],true)?1:0;
        $this->target->prepare("INSERT INTO arpa_subject_assignment(id,record_origin,request_id,officer_id,subject_id,subject_kind_snapshot,officer_exclusive_snapshot,province_location_id_snapshot,district_location_id_snapshot,asc_location_id,province_name_snapshot,district_name_snapshot,asc_dad_snapshot,asc_name_snapshot,subject_name_snapshot,context_snapshot_json,effective_from,legacy_history_only,legacy_exception,legacy_exception_codes_json,approved_by,approved_at,approval_timestamp_provenance,origin_metadata_json) VALUES(:id,'LEGACY_IMPORT',:request_id,:officer_id,:subject_id,:subject_kind,:exclusive,:province_id,:district_id,:asc_id,:province_name,:district_name,:asc_dad,:asc_name,:subject_name,:context,:effective_from,:history_only,:legacy_exception,:exception_codes,NULL,NULL,'UNAVAILABLE_FROM_LEGACY_SOURCE',:origin)")->execute(['id'=>$id,'request_id'=>$requestId,'officer_id'=>$r['officer_id'],'subject_id'=>$subject['id'],'subject_kind'=>$r['subject_kind'],'exclusive'=>$exclusive,'province_id'=>$r['province_location_id'],'district_id'=>$r['district_location_id'],'asc_id'=>$r['resolved_asc_id'],'province_name'=>$province['name_en']??null,'district_name'=>$district['name_en']??null,'asc_dad'=>$asc['dad_number'],'asc_name'=>$asc['name_en'],'subject_name'=>$subject['name_en'],'context'=>$this->json($r['location_provenance_json']),'effective_from'=>$r['effective_from'],'history_only'=>$r['legacy_history_only']?1:0,'legacy_exception'=>$r['historical_exception']?1:0,'exception_codes'=>$this->json($r['historical_exception_types_json']),'origin'=>$origin]);
        $period=null;if($r['subject_kind']==='SITHAMU'){$designation=$this->target->query("SELECT id,name_en FROM designation WHERE system_key='SITHAMU' AND active=1 AND approval_status='APPROVED'")->fetch();$period=$this->uuid();$this->target->prepare("INSERT INTO arpa_officer_sub_designation_period(id,record_origin,officer_id,designation_id,source_subject_assignment_id,asc_location_id,designation_key_snapshot,designation_name_snapshot,asc_dad_snapshot,asc_name_snapshot,effective_from,approved_by,approved_at,approval_timestamp_provenance,origin_metadata_json) VALUES(:id,'LEGACY_IMPORT',:officer_id,:designation_id,:assignment_id,:asc_id,'SITHAMU',:designation_name,:asc_dad,:asc_name,:effective_from,NULL,NULL,'UNAVAILABLE_FROM_LEGACY_SOURCE',:origin)")->execute(['id'=>$period,'officer_id'=>$r['officer_id'],'designation_id'=>$designation['id'],'assignment_id'=>$id,'asc_id'=>$r['resolved_asc_id'],'designation_name'=>$designation['name_en'],'asc_dad'=>$asc['dad_number'],'asc_name'=>$asc['name_en'],'effective_from'=>$r['effective_from'],'origin'=>$origin]);}
        $closure=null;if($r['effective_to']){$closure=$this->uuid();$reason=$this->reason($r['legacy_reason_id']);$this->target->prepare("INSERT INTO arpa_subject_assignment_closure(id,record_origin,assignment_id,request_id,effective_to,end_reason_id,legacy_reason_id,legacy_reason_text,remarks,context_snapshot_json,approved_by,approved_at,approval_timestamp_provenance,origin_metadata_json) VALUES(:id,'LEGACY_IMPORT',:assignment_id,:request_id,:effective_to,:reason_id,:legacy_reason_id,:legacy_reason_text,'Imported reconciled legacy closure',:snapshot,NULL,NULL,'UNAVAILABLE_FROM_LEGACY_SOURCE',:origin)")->execute(['id'=>$closure,'assignment_id'=>$id,'request_id'=>$requestId,'effective_to'=>$r['effective_to'],'reason_id'=>$reason,'legacy_reason_id'=>$r['legacy_reason_id'],'legacy_reason_text'=>$r['legacy_reason_text'],'snapshot'=>$this->json($r['location_provenance_json']),'origin'=>$origin]);if($period){$subClose=$this->uuid();$this->target->prepare("INSERT INTO arpa_officer_sub_designation_closure(id,record_origin,sub_designation_period_id,source_subject_assignment_closure_id,effective_to,end_reason_id,approved_by,approved_at,approval_timestamp_provenance,origin_metadata_json) VALUES(:id,'LEGACY_IMPORT',:period_id,:closure_id,:effective_to,:reason_id,NULL,NULL,'UNAVAILABLE_FROM_LEGACY_SOURCE',:origin)")->execute(['id'=>$subClose,'period_id'=>$period,'closure_id'=>$closure,'effective_to'=>$r['effective_to'],'reason_id'=>$reason,'origin'=>$origin]);}}
        return [$id,$period,$closure];
    }

    private function insertWorkflow(string $table,string $requestId,array $workflow):int{$previous='CREATED';$count=0;foreach(self::WORKFLOW as $field=>[$action,$stage,$next]){$actor=$workflow[$field]??null;$user=$actor['target_user']['id']??null;if(!$user)continue;$this->target->prepare("INSERT INTO {$table}(record_origin,request_id,action,stage,user_id,comments,previous_status,new_status,action_at,timestamp_provenance,legacy_source_payload_json) VALUES('LEGACY_IMPORT',?,?,?,?,NULL,?,?,NULL,'UNAVAILABLE_FROM_LEGACY_SOURCE',?)")->execute([$requestId,$action,$stage,$user,$previous,$next,$this->json($actor)]);$previous=$next;$count++;}return $count;}
    private function decode(array $r):array{foreach(['historical_exception_types_json','current_conflict_types_json','blocker_types_json','source_references_json','workflow_json','location_provenance_json','source_provenance_json'] as $f)$r[$f]=json_decode((string)$r[$f],true)?:[];return $r;}
    private function officeCovers(array $office,string $officerId,?string $ascId,string $date):bool{if($ascId===null)return false;foreach($office[$officerId.'|'.$ascId]??[] as $period)if($period['effective_from']<=$date&&($period['effective_to']===null||$period['effective_to']>=$date))return true;return false;}
    private function workflowCount(array $r):int{$n=0;foreach(self::WORKFLOW as $field=>$_)if(!empty($r['workflow_json'][$field]['target_user']['id']))$n++;return $n;}
    private function targetWorkflowState(string $state):string{return match($state){'DRAFT'=>'CREATED','REJECTED_OR_RESET'=>'REJECTED',default=>in_array($state,['CREATED','SUBMITTED','ASC_VERIFIED','ASC_APPROVED','DISTRICT_VERIFIED','DISTRICT_APPROVED','NATIONAL_VERIFIED','NATIONAL_APPROVED','RETURNED','REJECTED'],true)?$state:'CREATED'};}
    private function profileExample(array $records):array{$out=[];foreach($records as $r)if($r['officer_dad_number']==='70045-0003443'&&in_array($r['effective_from'],['2025-01-01','2026-01-01'],true)&&in_array($r['appointment_type'],['PERMANENT','ACTING'],true))$out[]=['business_key'=>$r['reconciled_business_key'],'officer_dad_number'=>$r['officer_dad_number'],'officer_name'=>$r['officer_name'],'arpa_division'=>$r['resolved_arpa_name'],'appointment_type'=>$r['appointment_type'],'effective_from'=>$r['effective_from'],'source_current_classification'=>$r['current_classification'],'operational_projection'=>$r['operational_projection'],'legacy_history_only'=>$r['legacy_history_only'],'activation_block_reason'=>$r['activation_block_reason'],'exceptions'=>$r['historical_exception_types_json'],'source_references'=>$r['source_references_json']];return $out;}
    private function writeReport(array $summary,array $records,array $issues):string{$dir=BASE_PATH.'/storage/reports';if(!is_dir($dir))mkdir($dir,0770,true);$path=$dir.'/final-legacy-arpa-appointment-migration-dry-run-'.date('Ymd-His').'.json';$compact=array_map(fn(array $r):array=>['business_key'=>$r['reconciled_business_key'],'officer'=>$r['officer_dad_number'],'category'=>$r['assignment_category'],'type'=>$r['appointment_type']??$r['subject_kind'],'effective_from'=>$r['effective_from'],'effective_to'=>$r['effective_to'],'baseline_date'=>$r['baseline_date'],'baseline_classification'=>$r['baseline_classification'],'carried_into_baseline'=>$r['carried_into_baseline'],'migration_classification'=>$r['migration_classification'],'evidence_class'=>$r['special_evidence_class']??$r['location_confidence'],'resolved_asc_id'=>$r['resolved_asc_id'],'workflow_state'=>$r['workflow_state'],'operational_projection'=>$r['operational_projection'],'legacy_history_only'=>$r['legacy_history_only'],'activation_note'=>$r['activation_block_reason'],'manual_review_reasons'=>$r['manual_review_reasons'],'exceptions'=>$r['historical_exception_types_json'],'source_references'=>$r['source_references_json']],$records);file_put_contents($path,$this->json(['generated_at'=>date(DATE_ATOM),'summary'=>$summary,'issues'=>$issues,'records'=>$compact]),LOCK_EX);return $path;}
    private function subject(string $key):array{$s=$this->target->prepare("SELECT id,name_en FROM subject_master WHERE system_key=? AND active=1 AND approval_status='APPROVED'");$s->execute([$key]);$r=$s->fetch();if(!$r)throw new RuntimeException("Missing approved central subject {$key}.");return $r;}
    private function reason(?string $legacyId):?string{if(!$legacyId||!isset(self::REASONS[$legacyId]))return null;$s=$this->target->prepare("SELECT id FROM arpa_appointment_end_reason WHERE system_key=? AND active=1");$s->execute([self::REASONS[$legacyId]]);return $s->fetchColumn()?:null;}
    private function locations(array $ids):array{$ids=array_values(array_unique(array_filter($ids)));if(!$ids)return [];$s=$this->target->prepare('SELECT id,dad_number,name_en FROM location WHERE id IN ('.implode(',',array_fill(0,count($ids),'?')).')');$s->execute($ids);$out=[];foreach($s->fetchAll() as $r)$out[$r['id']]=$r;return $out;}
    private function uuid():string{return (string)$this->target->query('SELECT UUID()')->fetchColumn();}private function json(mixed $v):string{return json_encode($v,JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_INVALID_UTF8_SUBSTITUTE);}
}
