<?php
declare(strict_types=1);

namespace App\Services\LegacyAppointment;

use App\Core\ScopeService;
use DomainException;
use PDO;
use Throwable;

final class LegacyArpaAppointmentPreviewService
{
    public function __construct(private readonly PDO $source,private readonly PDO $target){}

    public function refreshIndex(): array
    {
        $staging='legacy_arpa_appointment_preview_staging';$this->target->exec("DROP TEMPORARY TABLE IF EXISTS {$staging}");$this->target->exec("CREATE TEMPORARY TABLE {$staging} LIKE legacy_arpa_appointment_preview");
        $sql="INSERT INTO {$staging}(reconciled_business_key,source_system,officer_id,legacy_officer_id,assignment_category,appointment_type,subject_kind,service_permanency_snapshot,service_permanency_source,effective_from,effective_to,legacy_reason_id,legacy_reason_text,workflow_state,legacy_operational_approval,current_classification,reconciliation_class,source_scope,location_confidence,asc_location_id,arpa_location_id,district_location_id,province_location_id,historical_exception,historical_exception_types_json,current_conflict,current_conflict_types_json,diagnostic_blocker,blocker_types_json,source_references_json,workflow_json,location_provenance_json,source_provenance_json,active,first_indexed_at,last_indexed_at) VALUES(".implode(',',array_fill(0,33,'?')).",1,NOW(),NOW())";
        $stmt=$this->target->prepare($sql);$json=fn($v)=>json_encode($v,JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_INVALID_UTF8_SUBSTITUTE);
        try{
            $summary=(new HistoricalArpaAppointmentDiagnosticService($this->source,$this->target))->run(function(array $r)use($stmt,$json):void{$stmt->execute([$r['reconciled_business_key'],$r['source_system'],$r['officer_id'],$r['legacy_officer_id'],$r['assignment_category'],$r['appointment_type'],$r['subject_kind'],$r['service_permanency_snapshot'],$r['service_permanency_source'],$r['effective_from'],$r['effective_to'],$r['legacy_reason_id'],$r['legacy_reason_text'],$r['workflow_state'],$r['legacy_operational_approval']?1:0,$r['current_classification'],$r['reconciliation_class'],$r['source_scope'],$r['location_confidence'],$r['asc_location_id'],$r['arpa_location_id'],$r['district_location_id'],$r['province_location_id'],$r['historical_exception']?1:0,$json($r['historical_exception_types']),$r['current_conflict']?1:0,$json($r['current_conflict_types']),$r['diagnostic_blocker']?1:0,$json($r['blocker_types']),$json($r['source_references']),$json($r['workflow']),$json($r['location_provenance']),$json($r['source_provenance'])]);});
            $count=(int)$this->target->query("SELECT COUNT(*) FROM {$staging}")->fetchColumn();$expected=array_sum($summary['deduplication']);if($count!==$expected)throw new DomainException("Preview index reconciliation produced {$count} records while the diagnostic produced {$expected} business records.");
            $this->target->beginTransaction();$this->target->exec('DELETE FROM legacy_arpa_appointment_preview');$this->target->exec("INSERT INTO legacy_arpa_appointment_preview SELECT * FROM {$staging}");$sync=$this->target->prepare('INSERT INTO legacy_arpa_appointment_preview_sync(singleton_id,reconciled_record_count,diagnostic_generated_at,source_old_count,source_2026_count,indexed_at) VALUES(1,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE reconciled_record_count=VALUES(reconciled_record_count),diagnostic_generated_at=VALUES(diagnostic_generated_at),source_old_count=VALUES(source_old_count),source_2026_count=VALUES(source_2026_count),indexed_at=NOW()');$sync->execute([$count,date('Y-m-d H:i:s',strtotime((string)$summary['generated_at'])),$summary['source']['tbl_officer_apoint_rows'],$summary['source']['tbl_officer_apoint_2026_rows']]);$this->target->commit();
            return ['count'=>$count,'summary'=>$summary];
        }catch(Throwable $e){if($this->target->inTransaction())$this->target->rollBack();throw $e;}finally{$this->target->exec("DROP TEMPORARY TABLE IF EXISTS {$staging}");}
    }

    public function summary(): array
    {
        $row=$this->target->query("SELECT COUNT(*) total,SUM(p.assignment_category='ARPA_DIVISION') arpa_division,SUM(p.subject_kind='AGRARIAN_BANK') agrarian_bank,SUM(p.subject_kind='SALES_SHOP') sales_shop,SUM(p.subject_kind='SITHAMU') sithamu,SUM(p.current_classification='HISTORICAL') historical,SUM(p.current_classification='CURRENT') current_candidates,SUM(p.effective_from<'2025-01-01' AND (p.effective_to IS NULL OR p.effective_to>='2025-01-01')) pre_baseline_carried_forward,SUM(p.effective_from>='2025-01-01') legacy_period,SUM(p.effective_from<'2025-01-01' AND p.effective_to<'2025-01-01') pre_baseline_history,SUM(p.effective_from IS NULL OR (p.assignment_category='ARPA_DIVISION' AND COALESCE(mr.selected_target_arpa_id,p.arpa_location_id,CASE WHEN p.location_confidence IN ('EXACT','STRONG_DERIVED') THEN JSON_UNQUOTE(JSON_EXTRACT(p.location_provenance_json,'$.target_context_id')) END) IS NULL) OR (p.assignment_category='ASC_FUNCTION' AND si.candidate_asc_id IS NULL AND LOWER(COALESCE(JSON_UNQUOTE(JSON_EXTRACT(si.candidate_evidence_json,'$.method')),'')) LIKE '%multiple%')) blockers FROM legacy_arpa_appointment_preview p LEFT JOIN legacy_arpa_reconciliation_item si ON si.reconciled_business_key=p.reconciled_business_key AND si.item_type='SPECIAL_ASC' AND si.active=1 LEFT JOIN legacy_arpa_reconciliation_item mi ON mi.reconciled_business_key=p.reconciled_business_key AND mi.item_type='MISSING_ARPA_LOCATION' AND mi.active=1 LEFT JOIN legacy_arpa_appointment_resolution mr ON mr.reconciliation_item_id=mi.id WHERE p.active=1")->fetch();return array_map('intval',$row?:[]);
    }

    public function summaryForUser(string $userId):array
    {
        if(!ScopeService::requiresGeographicRestriction($userId))return $this->summary();
        $with=ScopeService::visibleLocationsCte();$sql=$with." SELECT COUNT(*) total,SUM(p.assignment_category='ARPA_DIVISION') arpa_division,SUM(p.subject_kind='AGRARIAN_BANK') agrarian_bank,SUM(p.subject_kind='SALES_SHOP') sales_shop,SUM(p.subject_kind='SITHAMU') sithamu,SUM(p.current_classification='HISTORICAL') historical,SUM(p.current_classification='CURRENT') current_candidates,SUM(p.effective_from<'2025-01-01' AND (p.effective_to IS NULL OR p.effective_to>='2025-01-01')) pre_baseline_carried_forward,SUM(p.effective_from>='2025-01-01') legacy_period,SUM(p.effective_from<'2025-01-01' AND p.effective_to<'2025-01-01') pre_baseline_history,SUM(p.effective_from IS NULL OR (p.assignment_category='ARPA_DIVISION' AND COALESCE(mr.selected_target_arpa_id,p.arpa_location_id,CASE WHEN p.location_confidence IN ('EXACT','STRONG_DERIVED') THEN JSON_UNQUOTE(JSON_EXTRACT(p.location_provenance_json,'$.target_context_id')) END) IS NULL) OR (p.assignment_category='ASC_FUNCTION' AND si.candidate_asc_id IS NULL AND LOWER(COALESCE(JSON_UNQUOTE(JSON_EXTRACT(si.candidate_evidence_json,'$.method')),'')) LIKE '%multiple%')) blockers FROM legacy_arpa_appointment_preview p LEFT JOIN legacy_arpa_reconciliation_item si ON si.reconciled_business_key=p.reconciled_business_key AND si.item_type='SPECIAL_ASC' AND si.active=1 LEFT JOIN legacy_arpa_appointment_resolution sr ON sr.reconciliation_item_id=si.id LEFT JOIN legacy_arpa_reconciliation_item mi ON mi.reconciled_business_key=p.reconciled_business_key AND mi.item_type='MISSING_ARPA_LOCATION' AND mi.active=1 LEFT JOIN legacy_arpa_appointment_resolution mr ON mr.reconciliation_item_id=mi.id JOIN visible_locations vl ON vl.id=COALESCE(sr.selected_target_asc_id,si.candidate_asc_id,mr.selected_target_asc_id,p.asc_location_id) WHERE p.active=1";$s=$this->target->prepare($sql);$s->execute([$userId]);return array_map('intval',$s->fetch()?:[]);
    }

    public function record(string $key): array
    {
        if(preg_match('/^[a-f0-9]{64}$/',$key)!==1)throw new DomainException('Legacy appointment preview record was not found.');
        $sql="SELECT p.*,o.dad_number,o.nic,o.name_with_initials,o.full_name_en,c.name_en class_name,a.dad_number asc_number,a.name_en asc_name,ar.dad_number arpa_number,ar.name_en arpa_name,d.dad_number district_number,d.name_en district_name,pr.dad_number province_number,pr.name_en province_name,si.candidate_asc_id deterministic_asc_id,si.source_confidence candidate_evidence_class,si.candidate_evidence_json,COALESCE(sr.resolution_status,mr.resolution_status,cr.resolution_status) reconciliation_status,COALESCE(sr.selected_target_asc_id,si.candidate_asc_id,mr.selected_target_asc_id) confirmed_asc_id,mr.selected_target_arpa_id confirmed_arpa_id,cr.activation_decision,COALESCE(si.id,mi.id,ci.id) review_item_id FROM legacy_arpa_appointment_preview p JOIN officer o ON o.id=p.officer_id LEFT JOIN officer_class c ON c.id=o.class_id LEFT JOIN legacy_arpa_reconciliation_item si ON si.reconciled_business_key=p.reconciled_business_key AND si.item_type='SPECIAL_ASC' AND si.active=1 LEFT JOIN legacy_arpa_appointment_resolution sr ON sr.reconciliation_item_id=si.id LEFT JOIN legacy_arpa_reconciliation_item mi ON mi.reconciled_business_key=p.reconciled_business_key AND mi.item_type='MISSING_ARPA_LOCATION' AND mi.active=1 LEFT JOIN legacy_arpa_appointment_resolution mr ON mr.reconciliation_item_id=mi.id LEFT JOIN legacy_arpa_reconciliation_item ci ON ci.reconciled_business_key=p.reconciled_business_key AND ci.item_type='CURRENT_CONFLICT' AND ci.active=1 LEFT JOIN legacy_arpa_appointment_resolution cr ON cr.reconciliation_item_id=ci.id LEFT JOIN location a ON a.id=COALESCE(sr.selected_target_asc_id,si.candidate_asc_id,mr.selected_target_asc_id,p.asc_location_id) LEFT JOIN location ar ON ar.id=COALESCE(mr.selected_target_arpa_id,p.arpa_location_id) LEFT JOIN location d ON d.id=p.district_location_id LEFT JOIN location pr ON pr.id=p.province_location_id WHERE p.reconciled_business_key=? AND p.active=1";$s=$this->target->prepare($sql);$s->execute([$key]);$record=$s->fetch();if(!$record)throw new DomainException('Legacy appointment preview record was not found.');foreach(['historical_exception_types_json','current_conflict_types_json','blocker_types_json','source_references_json','workflow_json','location_provenance_json','source_provenance_json'] as $field)$record[$field]=json_decode((string)$record[$field],true)?:[];
        $record['baseline_date']=LegacyArpaMigrationPolicy::BASELINE_DATE;$record['baseline_classification']=LegacyArpaMigrationPolicy::periodClassification($record['effective_from'],$record['effective_to']);$record['baseline_label']=LegacyArpaMigrationPolicy::baselineLabel($record['baseline_classification']);$record['carried_into_baseline']=LegacyArpaMigrationPolicy::carriedIntoBaseline($record['effective_from'],$record['effective_to']);
        $candidateEvidence=json_decode((string)($record['candidate_evidence_json']??''),true)?:[];$ambiguous=str_contains(strtolower((string)($candidateEvidence['method']??'')),'multiple');$unresolved=[];foreach($record['blocker_types_json'] as $blocker){if($blocker==='ASC_REVIEW_REQUIRED'&&!$ambiguous)continue;if($blocker==='CURRENT_CONFLICT')continue;if($blocker==='MISSING_ARPA_LOCATION'&&$record['reconciliation_status']==='CONFIRMED')continue;$unresolved[]=$blocker;}if($record['effective_from']===null&&!in_array('MISSING_EFFECTIVE_FROM',$unresolved,true))$unresolved[]='MISSING_EFFECTIVE_FROM';$record['effective_blocker_types']=$unresolved;$record['effective_blocker']=$unresolved!==[];
        $sourceRows=[];foreach($record['source_references_json'] as $reference){[$table,$id]=explode(':',$reference,2);if(!in_array($table,['tbl_officer_apoint','tbl_officer_apoint_2026'],true))continue;$source=$this->source->prepare("SELECT auto_id,officer_id,officer_level,duty_type,location,appoint_date,appoint_end_date,appoint_end_reason,asc_approve,district_approve,national_approve,asc_varify_by,asc_approve_by,district_varify_by,district_approve_by,national_varify_by,national_approve_by,status,created_at,updated_at FROM `{$table}` WHERE auto_id=?");$source->execute([$id]);if($row=$source->fetch())$sourceRows[$reference]=$row;}$record['source_provenance_json']['source_records']=$sourceRows;return $record;
    }

    public function officerHistory(string $officerId): array
    {
        $s=$this->target->prepare("SELECT p.reconciled_business_key,p.assignment_category,p.appointment_type,p.subject_kind,p.effective_from,p.effective_to,p.current_classification,p.diagnostic_blocker,p.historical_exception,p.asc_location_id,a.name_en asc_name,ar.name_en arpa_name FROM legacy_arpa_appointment_preview p LEFT JOIN location a ON a.id=p.asc_location_id LEFT JOIN location ar ON ar.id=p.arpa_location_id WHERE p.officer_id=? AND p.active=1 ORDER BY p.effective_from,p.effective_to,p.reconciled_business_key");$s->execute([$officerId]);$rows=$s->fetchAll();foreach($rows as &$row){$row['baseline_classification']=LegacyArpaMigrationPolicy::periodClassification($row['effective_from'],$row['effective_to']);$row['baseline_label']=LegacyArpaMigrationPolicy::baselineLabel($row['baseline_classification']);}unset($row);return $rows;
    }

    public function locationOptions(string $type): array{$s=$this->target->prepare("SELECT l.id,l.dad_number,l.name_en FROM location l JOIN location_type t ON t.id=l.location_type_id WHERE t.system_key=? AND l.approval_status='APPROVED' ORDER BY l.name_en");$s->execute([$type]);return $s->fetchAll();}
    public function officerOptions(): array{return $this->target->query("SELECT DISTINCT o.id,o.dad_number,o.name_with_initials FROM legacy_arpa_appointment_preview p JOIN officer o ON o.id=p.officer_id WHERE p.active=1 ORDER BY o.name_with_initials")->fetchAll();}
}
