<?php
declare(strict_types=1);

namespace App\Services;

use PDO;
use RuntimeException;

final class OfficerProfileService
{
    public function __construct(private readonly PDO $pdo){}

    public function profile(string $officerId,array $allowedOfficeIds=[],?array $allowedAscIds=null):array
    {
        $s=$this->pdo->prepare("SELECT o.*,t.name_en title_name,cs.name_en civil_status_name,d.name_en designation_name,d.system_key designation_key,c.name_en class_name,os.name_en officer_status_name,po.dad_number primary_office_dad,po.name_en primary_office_name FROM officer o LEFT JOIN hr_title t ON t.id=o.title_id LEFT JOIN civil_status cs ON cs.id=o.civil_status_id LEFT JOIN designation d ON d.id=o.primary_designation_id LEFT JOIN officer_class c ON c.id=o.class_id LEFT JOIN officer_status os ON os.id=o.officer_status_id LEFT JOIN office po ON po.id=o.primary_office_id WHERE o.id=?");$s->execute([$officerId]);$officer=$s->fetch();if(!$officer)throw new RuntimeException('Officer was not found.');
        $officeSql="SELECT a.*,ofc.dad_number office_dad,ofc.name_en office_name,ot.name_en office_type,l.dad_number location_dad,l.name_en location_name,CASE WHEN a.approval_status='APPROVED' AND a.active=1 AND a.effective_from<=CURRENT_DATE() AND (a.effective_to IS NULL OR a.effective_to>=CURRENT_DATE()) THEN 1 ELSE 0 END is_current FROM officer_office_assignment a JOIN office ofc ON ofc.id=a.office_id JOIN office_type ot ON ot.id=ofc.office_type_id LEFT JOIN location l ON l.id=ofc.linked_location_id WHERE a.officer_id=?";$params=[$officerId];if($allowedOfficeIds!==[]){$officeSql.=' AND a.office_id IN ('.implode(',',array_fill(0,count($allowedOfficeIds),'?')).')';$params=array_merge($params,$allowedOfficeIds);}$officeSql.=' ORDER BY is_current DESC,a.effective_from DESC,a.id';$s=$this->pdo->prepare($officeSql);$s->execute($params);$officeRows=$s->fetchAll();
        [$operationalAppointments,$appointmentWorkflow]=$this->operationalAppointments($officerId,$allowedAscIds);[$operationalSubjects,$subjectWorkflow]=$this->operationalSubjects($officerId,$allowedAscIds);
        $legacy=$this->legacyHistory($officerId,$allowedAscIds);
        return ['officer'=>$officer,'service_permanency_evidence'=>$this->servicePermanencyEvidence($officerId),'current_offices'=>array_values(array_filter($officeRows,fn($r)=>(int)$r['is_current']===1)),'historical_offices'=>array_values(array_filter($officeRows,fn($r)=>(int)$r['is_current']!==1)),'current_appointments'=>$this->period($operationalAppointments,'CURRENT'),'future_appointments'=>$this->period($operationalAppointments,'FUTURE'),'previous_appointments'=>$this->period($operationalAppointments,'PREVIOUS'),'current_subjects'=>$this->period($operationalSubjects,'CURRENT'),'future_subjects'=>$this->period($operationalSubjects,'FUTURE'),'previous_subjects'=>$this->period($operationalSubjects,'PREVIOUS'),'appointment_workflow'=>$appointmentWorkflow,'subject_workflow'=>$subjectWorkflow,'legacy_current'=>$this->period($legacy,'CURRENT'),'legacy_future'=>$this->period($legacy,'FUTURE'),'legacy_previous'=>$this->period($legacy,'PREVIOUS'),'appointment_corrections'=>(new ArpaAppointmentDataIssueCorrectionService($this->pdo))->correctionsForOfficer($officerId,$allowedAscIds)];
    }

    private function operationalAppointments(string $id,?array $ascIds):array
    {
        $scope=$this->scopeSql('a.asc_location_id',$ascIds);$approved="((a.record_origin='NATIVE' AND r.workflow_status='NATIONAL_APPROVED') OR (a.record_origin='LEGACY_IMPORT' AND r.workflow_status IN('DISTRICT_APPROVED','NATIONAL_VERIFIED','NATIONAL_APPROVED')))";$s=$this->pdo->prepare("SELECT a.id,a.request_id,a.record_origin,a.appointment_type,a.service_permanency_snapshot,a.service_permanency_source,a.asc_name_snapshot,a.district_name_snapshot,a.arpa_name_snapshot,a.effective_from,c.effective_to,COALESCE(er.name_en,c.legacy_reason_text) end_reason,r.workflow_status,a.letter_reference_id,a.letter_type,a.letter_date,CASE WHEN a.legacy_history_only=0 AND {$approved} AND a.effective_from>CURRENT_DATE() THEN 'FUTURE' WHEN a.legacy_history_only=0 AND {$approved} AND a.effective_from<=CURRENT_DATE() AND (c.effective_to IS NULL OR c.effective_to>=CURRENT_DATE()) THEN 'CURRENT' ELSE 'PREVIOUS' END profile_period FROM arpa_division_appointment a JOIN arpa_division_appointment_request r ON r.id=a.request_id LEFT JOIN arpa_division_appointment_closure c ON c.appointment_id=a.id LEFT JOIN arpa_appointment_end_reason er ON er.id=c.end_reason_id WHERE a.officer_id=?{$scope['sql']} ORDER BY FIELD(profile_period,'CURRENT','FUTURE','PREVIOUS'),a.effective_from DESC");$s->execute(array_merge([$id],$scope['params']));$rows=$s->fetchAll();return [$rows,$this->workflow('arpa_appointment_workflow_action',array_column($rows,'request_id'))];
    }
    private function operationalSubjects(string $id,?array $ascIds):array
    {
        $scope=$this->scopeSql('a.asc_location_id',$ascIds);$approved="((a.record_origin='NATIVE' AND r.workflow_status='NATIONAL_APPROVED') OR (a.record_origin='LEGACY_IMPORT' AND r.workflow_status IN('DISTRICT_APPROVED','NATIONAL_VERIFIED','NATIONAL_APPROVED')))";$s=$this->pdo->prepare("SELECT a.id,a.request_id,a.record_origin,a.subject_kind_snapshot,a.subject_name_snapshot,a.asc_name_snapshot,a.district_name_snapshot,a.effective_from,c.effective_to,COALESCE(er.name_en,c.legacy_reason_text) end_reason,r.workflow_status,sp.designation_name_snapshot sub_designation_name,a.letter_reference_id,a.letter_type,a.letter_date,CASE WHEN a.legacy_history_only=0 AND {$approved} AND a.effective_from>CURRENT_DATE() THEN 'FUTURE' WHEN a.legacy_history_only=0 AND {$approved} AND a.effective_from<=CURRENT_DATE() AND (c.effective_to IS NULL OR c.effective_to>=CURRENT_DATE()) THEN 'CURRENT' ELSE 'PREVIOUS' END profile_period FROM arpa_subject_assignment a JOIN arpa_subject_assignment_request r ON r.id=a.request_id LEFT JOIN arpa_subject_assignment_closure c ON c.assignment_id=a.id LEFT JOIN arpa_appointment_end_reason er ON er.id=c.end_reason_id LEFT JOIN arpa_officer_sub_designation_period sp ON sp.source_subject_assignment_id=a.id WHERE a.officer_id=?{$scope['sql']} ORDER BY FIELD(profile_period,'CURRENT','FUTURE','PREVIOUS'),a.effective_from DESC");$s->execute(array_merge([$id],$scope['params']));$rows=$s->fetchAll();return [$rows,$this->workflow('arpa_subject_workflow_action',array_column($rows,'request_id'))];
    }
    private function workflow(string $table,array $requestIds):array
    {
        if($requestIds===[])return [];$marks=implode(',',array_fill(0,count($requestIds),'?'));$s=$this->pdo->prepare("SELECT w.*,u.display_name,u.username FROM {$table} w JOIN system_user u ON u.id=w.user_id WHERE w.request_id IN ({$marks}) ORDER BY w.request_id,w.id");$s->execute($requestIds);$out=[];foreach($s->fetchAll() as $row)$out[$row['request_id']][]=$row;return $out;
    }
    private function legacyHistory(string $id,?array $ascIds):array
    {
        $scope=$this->scopeSql('COALESCE(sr.selected_target_asc_id,p.asc_location_id)',$ascIds);$sql="SELECT p.*,a.name_en asc_name,ar.name_en arpa_name,d.name_en district_name,cr.activation_decision FROM legacy_arpa_appointment_preview p LEFT JOIN location a ON a.id=p.asc_location_id LEFT JOIN location ar ON ar.id=p.arpa_location_id LEFT JOIN location d ON d.id=p.district_location_id LEFT JOIN legacy_arpa_reconciliation_item si ON si.reconciled_business_key=p.reconciled_business_key AND si.item_type='SPECIAL_ASC' AND si.active=1 LEFT JOIN legacy_arpa_appointment_resolution sr ON sr.reconciliation_item_id=si.id LEFT JOIN legacy_arpa_reconciliation_item ci ON ci.reconciled_business_key=p.reconciled_business_key AND ci.item_type='CURRENT_CONFLICT' AND ci.active=1 LEFT JOIN legacy_arpa_appointment_resolution cr ON cr.reconciliation_item_id=ci.id WHERE p.officer_id=? AND p.active=1{$scope['sql']} AND NOT EXISTS(SELECT 1 FROM legacy_arpa_appointment_business_record br WHERE br.reconciled_business_key=p.reconciled_business_key) ORDER BY p.effective_from DESC,p.reconciled_business_key";$s=$this->pdo->prepare($sql);$s->execute(array_merge([$id],$scope['params']));$rows=$s->fetchAll();foreach($rows as &$row){foreach(['workflow_json','source_references_json','blocker_types_json','historical_exception_types_json'] as $f)$row[$f]=json_decode((string)$row[$f],true)?:[];$approved=(int)$row['legacy_operational_approval']===1&&$row['activation_decision']!=='PRESERVE_HISTORY_ONLY';if($approved&&$row['effective_from']!==null&&$row['effective_from']>date('Y-m-d'))$row['profile_period']='FUTURE';else{$current=$row['current_classification']==='CURRENT'&&$approved&&$row['effective_from']!==null&&$row['effective_from']<=date('Y-m-d')&&($row['effective_to']===null||$row['effective_to']>=date('Y-m-d'));$row['profile_period']=$current?'CURRENT':'PREVIOUS';}}unset($row);return $rows;
    }
    private function period(array $rows,string $period):array{return array_values(array_filter($rows,fn($row)=>$row['profile_period']===$period));}
    private function servicePermanencyEvidence(string $officerId):?array
    {
        $s=$this->pdo->prepare('SELECT source_system,source_table,legacy_officer_ids_json,resolved_fields_json,source_rows_json,created_at FROM legacy_officer_personnel_provenance WHERE officer_id=? ORDER BY created_at DESC,id DESC LIMIT 1');$s->execute([$officerId]);$row=$s->fetch();if(!$row)return null;
        $resolved=json_decode((string)$row['resolved_fields_json'],true)?:[];$sources=json_decode((string)$row['source_rows_json'],true)?:[];$legacyValues=[];$legacyDates=[];foreach($sources as $source){$value=trim((string)($source['permanent_or_not']??''));if($value!=='')$legacyValues[$value]=true;$date=trim((string)($source['permanented_date']??''));if($date!==''&&!str_starts_with($date,'0000-00-00'))$legacyDates[substr($date,0,10)]=true;}
        return ['source_system'=>$row['source_system'],'source_table'=>$row['source_table'],'legacy_officer_ids'=>json_decode((string)$row['legacy_officer_ids_json'],true)?:[],'legacy_values'=>array_keys($legacyValues),'legacy_permanented_dates'=>array_keys($legacyDates),'resolved_permanency'=>$resolved['arpa_service_permanency']??null,'resolved_permanented_date'=>$resolved['service_permanented_date']??null,'recorded_at'=>$row['created_at']];
    }
    private function scopeSql(string $column,?array $ids):array{if($ids===null)return ['sql'=>'','params'=>[]];if($ids===[])return ['sql'=>' AND 1=0','params'=>[]];return ['sql'=>' AND '.$column.' IN ('.implode(',',array_fill(0,count($ids),'?')).')','params'=>array_values($ids)];}
}
