<?php if(($dashboard['mode']??'ENTERPRISE')==='ENTERPRISE'): ?>
<div class="page-heading"><div><div class="breadcrumb-lite">Dashboard</div><h1>DEMS Dashboard</h1><p>Enterprise master data, officer identity and user access management.</p></div></div>
<div class="row g-3"><?php foreach(['locations'=>['Locations',null],'offices'=>['Offices',null],'officers'=>['Officers',null],'active_users'=>['Active Users','Enabled, login-capable operational identities'],'historical_users'=>['Historical Users','Disabled legacy identities retained for audit history'],'total_user_identities'=>['Total User Identities','All current and historical system identities']] as $k=>[$label,$description]): ?><div class="col-12 col-sm-6 col-xl-4"><div class="stat-card h-100"><div class="text-muted small"><?= e($label) ?></div><div class="display-6 fw-bold"><?= number_format((int)$counts[$k]) ?></div><?php if($description): ?><div class="small text-muted mt-1"><?= e($description) ?></div><?php endif; ?></div></div><?php endforeach; ?></div>
<?php else: $profile=$dashboard['profile'];$primary=$profile['primary']??null;$level=$profile['level'];$scopeName=$primary['name_en']??'Authorized Organization';$scopeDad=$primary['dad_number']??''; ?>
<div class="page-heading"><div><div class="breadcrumb-lite">Dashboard / <?= e($level) ?></div><h1><?= e($scopeName) ?><?= $level==='ASC'?' Agrarian Service Center':'' ?> Dashboard</h1><p><?= e($scopeDad) ?> &middot; Operational information within your approved active organizational scope.</p></div></div>
<div class="row g-3 mb-4"><?php foreach(['arpa_divisions'=>'ARPA Divisions','officers_assigned'=>'Officers Assigned to ASC Office','arpa_officers'=>'ARPA Officers','current_appointments'=>'Current ARPA Appointments','pending_requests'=>'Pending Appointment Requests','subject_assignments'=>'ASC Subject Assignments'] as $key=>$label): ?><div class="col-12 col-sm-6 col-xl-4"><div class="stat-card h-100"><div class="text-muted small"><?= e($label) ?></div><div class="display-6 fw-bold"><?= number_format((int)($counts[$key]??0)) ?></div></div></div><?php endforeach; ?></div>
<div class="row g-3">
  <div class="col-12 col-xl-6"><div class="card h-100 p-3"><h2 class="h5">ARPA Appointment Mix</h2><canvas class="dems-chart" data-chart-source="appointment-mix" data-chart-type="doughnut" aria-label="ARPA appointment mix chart"></canvas><div class="dems-chart-empty text-muted">No operational appointment data is available for this <?= $level==='ASC'?'ASC':'scope' ?> yet.</div><script nonce="<?= e(App\Core\SecurityHeaders::nonce()) ?>" type="application/json" id="appointment-mix"><?= json_encode($dashboard['charts']['appointment_mix'],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script></div></div>
  <div class="col-12 col-xl-6"><div class="card h-100 p-3"><h2 class="h5">ARPA Divisions / Officer Coverage</h2><canvas class="dems-chart" data-chart-source="division-coverage" data-chart-type="horizontalBar" aria-label="ARPA Division officer coverage horizontal bar chart"></canvas><script nonce="<?= e(App\Core\SecurityHeaders::nonce()) ?>" type="application/json" id="division-coverage"><?= json_encode($dashboard['charts']['division_coverage'],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script></div></div>
  <?php if(array_sum($dashboard['charts']['subject_mix'])>0): ?><div class="col-12"><div class="card p-3"><h2 class="h5">ASC Subject Assignments</h2><canvas class="dems-chart" data-chart-source="subject-mix" data-chart-type="bar" aria-label="ASC subject assignment chart"></canvas><script nonce="<?= e(App\Core\SecurityHeaders::nonce()) ?>" type="application/json" id="subject-mix"><?= json_encode($dashboard['charts']['subject_mix'],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script></div></div><?php endif; ?>
</div>
<?php if(is_array($dashboard['legacy'])): ?><div class="card border-warning mt-4"><div class="card-body"><div class="badge text-bg-warning mb-2">LEGACY / NOT YET MIGRATED</div><h2 class="h5">Legacy Appointment Preview</h2><div class="row g-3"><?php foreach(['total'=>'Reconciled Records','historical'=>'Historical','current_candidates'=>'Current Candidates','blockers'=>'Migration Blockers'] as $key=>$label): ?><div class="col-6 col-lg-3"><div class="small text-muted"><?= e($label) ?></div><div class="h3 mb-0"><?= number_format((int)($dashboard['legacy'][$key]??0)) ?></div></div><?php endforeach; ?></div></div></div><?php endif; ?>
<?php endif; ?>
