<?php
declare(strict_types=1);
namespace App\Services\LegacyOfficer;

use PDO;
use RuntimeException;
use Throwable;

/**
 * Reconciles current ARPA Division evidence to one ASC Office membership.
 * Special functions and tbl_officer.appoint_location_id are deliberately excluded.
 */
final class LegacyArpaCurrentOfficeBackfillService
{
    private const SOURCE_SYSTEM='AGRARIANADMIN_HR';
    private const SOURCE_TABLE='tbl_officer_apoint_2026';
    public function __construct(private readonly PDO $source,private readonly PDO $target,private readonly string $asOf){}

    public function dryRun():array
    {
        $this->assertDate($this->asOf);$sourceBefore=$this->sourceState();$targetBefore=$this->targetState();
        $rows=$this->qualifyingRows();$special=$this->specialFunctionCounts();$byLegacy=[];$sourceAscs=[];
        foreach($rows as $row){$legacy=(string)$row['officer_id'];$byLegacy[$legacy]['rows'][]=$row;$asc=$this->positive($row['legacy_asc_id']);if($asc!==null){$byLegacy[$legacy]['ascs'][$asc]=true;$sourceAscs[$asc]=true;}}
        $officerRefs=$this->officerReferences();$ascRefs=$this->ascReferences();$offices=$this->ascOffices();$targetOfficers=$this->targetOfficers();$current=$this->currentAssignments();
        $legacyPlans=[];$counts=['EXACT_ONE_ASC'=>0,'MULTIPLE_ASC'=>0,'NO_ASC'=>0,'target_officer_unresolved'=>0,'target_asc_unresolved'=>0,'target_asc_office_unresolved'=>0];
        foreach($byLegacy as $legacyId=>$evidence){
            $ascIds=array_keys($evidence['ascs']??[]);$class=self::classifyAscEvidence($ascIds);$counts[$class]++;
            $targetIds=array_keys($officerRefs[$legacyId]??[]);$targetOfficer=count($targetIds)===1?$targetIds[0]:null;if($targetOfficer===null)$counts['target_officer_unresolved']++;
            $legacyAsc=$class==='EXACT_ONE_ASC'?$ascIds[0]:null;$targetAsc=$legacyAsc!==null?($ascRefs[$legacyAsc]??null):null;if($legacyAsc!==null&&$targetAsc===null)$counts['target_asc_unresolved']++;
            $office=$targetAsc!==null?($offices[$targetAsc]??null):null;if($targetAsc!==null&&$office===null)$counts['target_asc_office_unresolved']++;
            $legacyPlans[$legacyId]=['legacy_officer_id'=>$legacyId,'classification'=>$class,'legacy_asc_ids'=>$ascIds,'target_officer_id'=>$targetOfficer,'legacy_asc_id'=>$legacyAsc,'target_asc_id'=>$targetAsc,'office'=>$office,'rows'=>$evidence['rows']];
        }

        // Verified aliases consolidate at the target Officer before an assignment is proposed.
        $byTarget=[];foreach($legacyPlans as $plan)if($plan['target_officer_id']!==null){$target=$plan['target_officer_id'];$byTarget[$target]['legacy_ids'][]=$plan['legacy_officer_id'];$byTarget[$target]['plans'][]=$plan;if($plan['target_asc_id']!==null)$byTarget[$target]['target_ascs'][$plan['target_asc_id']]=true;}
        $proposals=[];$already=[];$manual=[];$byAsc=[];$existingPrimaryReview=0;$otherAsc=0;$otherConcurrent=0;
        foreach($byTarget as $targetId=>$group){
            $targetAscs=array_keys($group['target_ascs']??[]);if(count($targetAscs)!==1){$manual[]=['target_officer_id'=>$targetId,'legacy_officer_ids'=>$group['legacy_ids'],'reason'=>count($targetAscs)>1?'ALIASES_RESOLVE_MULTIPLE_ASC':'NO_RESOLVED_TARGET_ASC'];continue;}
            $targetAsc=$targetAscs[0];$office=$offices[$targetAsc]??null;if($office===null){$manual[]=['target_officer_id'=>$targetId,'legacy_officer_ids'=>$group['legacy_ids'],'reason'=>'TARGET_ASC_OFFICE_UNRESOLVED'];continue;}
            $support=[];foreach($group['plans'] as $plan)if($plan['target_asc_id']===$targetAsc)array_push($support,...$plan['rows']);if($support===[])continue;
            $existing=$current[$targetId]??[];$same=array_values(array_filter($existing,fn($a)=>$a['office_id']===$office['id']));$primary=array_values(array_filter($existing,fn($a)=>(int)$a['is_primary']===1));$differentAsc=array_values(array_filter($existing,fn($a)=>$a['office_type_key']==='ASC_OFFICE'&&$a['office_id']!==$office['id']));
            if($same!==[]){$already[]=['target_officer_id'=>$targetId,'office_id'=>$office['id'],'legacy_officer_ids'=>$group['legacy_ids']];continue;}
            $primaryProposal=$primary===[];$existingPrimaryReview+=!$primaryProposal?1:0;$otherAsc+=count($differentAsc)>0?1:0;$otherConcurrent+=count($existing)>0?1:0;
            $divisions=[];$duty=[];$sourceIds=[];foreach($support as $row){$divisions[(string)$row['arpa_name']]=true;$duty[$this->dutyName($row['duty_type'])]=true;$sourceIds[]=(int)$row['auto_id'];}
            sort($sourceIds,SORT_NUMERIC);$officer=$targetOfficers[$targetId]??[];
            $proposal=['target_officer_id'=>$targetId,'officer_dad'=>$officer['dad_number']??null,'officer_name'=>$officer['name_with_initials']??null,'nic'=>$officer['nic']??null,'legacy_officer_ids'=>$group['legacy_ids'],'legacy_asc_id'=>$this->legacyAscId($support),'target_asc_id'=>$targetAsc,'asc_dad'=>$office['asc_dad'],'asc_name'=>$office['asc_name'],'office_id'=>$office['id'],'office_dad'=>$office['dad_number'],'office_name'=>$office['name_en'],'supporting_divisions'=>array_keys($divisions),'duty_types'=>array_keys($duty),'supporting_row_count'=>count($support),'source_record_ids'=>$sourceIds,'existing_assignments'=>array_map(fn($a)=>$a['office_dad'].' - '.$a['office_name'],$existing),'primary_status'=>$primaryProposal?'PROPOSE_AS_PRIMARY':'EXISTING_PRIMARY_REVIEW','proposed_action'=>'CREATE_APPROVED_CURRENT_STATE_ASSIGNMENT'];
            $proposals[]=$proposal;$byAsc[$targetAsc]['asc_dad']=$office['asc_dad'];$byAsc[$targetAsc]['asc_name']=$office['asc_name'];$byAsc[$targetAsc]['office_dad']=$office['dad_number'];$byAsc[$targetAsc]['office_name']=$office['name_en'];$byAsc[$targetAsc]['officers'][$targetId]=true;
        }
        foreach($byAsc as &$a){$a['distinct_officers']=count($a['officers']);unset($a['officers']);}unset($a);usort($byAsc,fn($a,$b)=>strcmp($a['asc_dad'],$b['asc_dad']));
        $kurunegala=array_values(array_filter($proposals,fn($p)=>$p['asc_dad']==='70004-0000389'));
        $unresolved=count($manual)+$counts['target_officer_unresolved']+$counts['target_asc_unresolved']+$counts['target_asc_office_unresolved'];
        $summary=['as_of'=>$this->asOf,'effective_from_policy'=>'Current-state snapshot as-of date; not represented as historical Office start date','source'=>['qualifying_appointment_rows'=>count($rows),'distinct_legacy_officers'=>count($byLegacy),'distinct_target_officers'=>count($byTarget),'distinct_ascs'=>count($sourceAscs)],'classification'=>$counts,'existing'=>['already_assigned'=>count($already),'assigned_to_another_asc_office'=>$otherAsc,'with_other_concurrent_office_assignments'=>$otherConcurrent,'existing_primary_review'=>$existingPrimaryReview],'projection'=>['would_create'=>count($proposals),'manual_review'=>count($manual),'true_execution_blockers'=>$unresolved,'unresolved_rows_excluded_deterministically'=>$unresolved],'special_functions_excluded'=>$special,'by_asc'=>$byAsc,'proposals'=>$proposals,'already_assigned'=>$already,'manual_review'=>$manual,'kurunegala'=>$kurunegala,'zero_write_verification'=>['source_unchanged'=>$sourceBefore===$this->sourceState(),'target_unchanged'=>$targetBefore===$this->targetState()]];
        $summary['reports']=$this->writeReports($summary);return $summary;
    }

    public function execute(bool $excludeUnresolved=false):array
    {
        $report=$this->dryRun();$excluded=(int)$report['projection']['unresolved_rows_excluded_deterministically'];if($excluded>0&&!$excludeUnresolved)throw new RuntimeException("Execution refused: {$excluded} unresolved/ambiguous classifications exist. Re-run with explicit deterministic exclusion after review.");
        $runId=(string)$this->target->query('SELECT UUID()')->fetchColumn();$run=$this->target->prepare("INSERT INTO legacy_arpa_office_backfill_run(id,source_system,source_table,as_of_date,status,qualifying_source_rows,distinct_legacy_officers,distinct_target_officers,distinct_ascs) VALUES(?,?,?,?,'RUNNING',?,?,?,?)");$run->execute([$runId,self::SOURCE_SYSTEM,self::SOURCE_TABLE,$this->asOf,$report['source']['qualifying_appointment_rows'],$report['source']['distinct_legacy_officers'],$report['source']['distinct_target_officers'],$report['source']['distinct_ascs']]);
        $this->target->beginTransaction();$created=0;$primarySynchronized=0;
        try{
            $insert=$this->target->prepare("INSERT INTO officer_office_assignment(id,officer_id,office_id,effective_from,is_primary,active,record_origin,source_system,source_table,source_evidence_json,legacy_backfill_run_id,approval_status,reason,official_reference,remarks,approved_at,approval_timestamp_provenance,version) VALUES(?,?,?,?,?,1,'LEGACY_CURRENT_STATE_BACKFILL',?,?,?,?, 'APPROVED',?,?,?,NULL,'UNAVAILABLE_CURRENT_STATE_BACKFILL',0)");
            foreach($report['proposals'] as $p){$lock=$this->target->prepare('SELECT id,primary_office_id FROM officer WHERE id=? FOR UPDATE');$lock->execute([$p['target_officer_id']]);$officer=$lock->fetch();if(!$officer)continue;$same=$this->target->prepare("SELECT COUNT(*) FROM officer_office_assignment WHERE officer_id=? AND office_id=? AND active=1 AND approval_status='APPROVED' AND effective_from<=? AND (effective_to IS NULL OR effective_to>=?) FOR UPDATE");$same->execute([$p['target_officer_id'],$p['office_id'],$this->asOf,$this->asOf]);if((int)$same->fetchColumn()>0)continue;
                $primary=$p['primary_status']==='PROPOSE_AS_PRIMARY';$evidence=['source'=>'LEGACY_ARPA_2026_CURRENT_STATE','evidence'=>'ARPA_DIVISION_TO_ASC','as_of'=>$this->asOf,'legacy_officer_ids'=>$p['legacy_officer_ids'],'legacy_asc_id'=>$p['legacy_asc_id'],'source_record_ids'=>$p['source_record_ids'],'supporting_rows'=>$p['supporting_row_count'],'effective_date_provenance'=>'CURRENT_STATE_BACKFILL_AS_OF_NOT_HISTORICAL_START'];
                $id=(string)$this->target->query('SELECT UUID()')->fetchColumn();$insert->execute([$id,$p['target_officer_id'],$p['office_id'],$this->asOf,$primary?1:0,self::SOURCE_SYSTEM,self::SOURCE_TABLE,json_encode($evidence,JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE),$runId,'Current organizational Office inferred from exact approved/current 2026 ARPA Division evidence.','LEGACY_ARPA_2026_CURRENT_STATE','Effective date is the controlled current-state backfill as-of date; it is not asserted as the historical Office joining date.']);
                $state=$this->target->prepare('SELECT * FROM officer_office_assignment WHERE id=?');$state->execute([$id]);$this->target->prepare("INSERT INTO officer_office_assignment_audit(assignment_id,action_key,new_state_json,reason,actor_user_id) VALUES(?,'LEGACY_CURRENT_STATE_BACKFILLED',?, ?,NULL)")->execute([$id,json_encode($state->fetch(),JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE),'Controlled current-state backfill; legacy source contains no authoritative Office-assignment creator or approval timestamp.']);
                if($primary){$sync=$this->target->prepare('UPDATE officer SET primary_office_id=? WHERE id=? AND primary_office_id IS NULL');$sync->execute([$p['office_id'],$p['target_officer_id']]);$primarySynchronized+=$sync->rowCount();}$created++;
            }
            $this->target->prepare("UPDATE legacy_arpa_office_backfill_run SET status='COMPLETED',created_assignments=?,synchronized_primary_offices=?,completed_at=NOW() WHERE id=?")->execute([$created,$primarySynchronized,$runId]);$this->target->commit();return ['run_id'=>$runId,'created'=>$created,'primary_synchronized'=>$primarySynchronized,'dry_run'=>$report];
        }catch(Throwable $e){if($this->target->inTransaction())$this->target->rollBack();$this->target->prepare("UPDATE legacy_arpa_office_backfill_run SET status='FAILED',error_message=?,completed_at=NOW() WHERE id=?")->execute([$e->getMessage(),$runId]);throw $e;}
    }

    public static function classifyAscEvidence(array $ascIds):string{$ids=array_values(array_unique(array_filter(array_map('strval',$ascIds),fn($v)=>$v!==''&&$v!=='0')));return count($ids)===0?'NO_ASC':(count($ids)===1?'EXACT_ONE_ASC':'MULTIPLE_ASC');}
    private function qualifyingRows():array{$s=$this->source->prepare("SELECT p.auto_id,p.officer_id,p.duty_type,p.location,p.appoint_date,p.appoint_end_date,p.status,p.district_approve,p.national_approve,a.auto_id legacy_arpa_id,a.arpa_code,a.arpa_name,a.asc_id legacy_asc_id,s.asc_code,s.asc_name FROM tbl_officer_apoint_2026 p LEFT JOIN tbl_arpa a ON a.auto_id=p.location LEFT JOIN tbl_asc s ON s.auto_id=a.asc_id WHERE LOWER(TRIM(p.officer_level))='arpa division' AND p.status=1 AND p.district_approve=2 AND p.appoint_date IS NOT NULL AND p.appoint_date<=? AND (p.appoint_end_date IS NULL OR p.appoint_end_date='0000-00-00' OR p.appoint_end_date>=?) ORDER BY p.officer_id,p.auto_id");$s->execute([$this->asOf,$this->asOf]);return $s->fetchAll();}
    private function specialFunctionCounts():array{$s=$this->source->prepare("SELECT LOWER(TRIM(officer_level)) kind,COUNT(*) rows_count,COUNT(DISTINCT officer_id) officer_count FROM tbl_officer_apoint_2026 WHERE LOWER(TRIM(officer_level)) IN('agrarian bank','sales shop','sithamu') AND status=1 AND district_approve=2 AND appoint_date IS NOT NULL AND appoint_date<=? AND (appoint_end_date IS NULL OR appoint_end_date='0000-00-00' OR appoint_end_date>=?) GROUP BY LOWER(TRIM(officer_level))");$s->execute([$this->asOf,$this->asOf]);$out=[];foreach($s->fetchAll() as $r)$out[strtoupper(str_replace(' ','_',$r['kind']))]=['rows'=>(int)$r['rows_count'],'distinct_officers'=>(int)$r['officer_count']];return $out;}
    private function officerReferences():array{$s=$this->target->prepare("SELECT legacy_officer_id,officer_id FROM legacy_officer_reference WHERE source_system=? AND source_table='tbl_officer'");$s->execute([self::SOURCE_SYSTEM]);$out=[];foreach($s->fetchAll() as $r)$out[(string)$r['legacy_officer_id']][(string)$r['officer_id']]=true;return $out;}
    private function ascReferences():array{$s=$this->target->prepare("SELECT legacy_id,location_id FROM legacy_location_reference WHERE source_system=? AND source_table='tbl_asc'");$s->execute([self::SOURCE_SYSTEM]);$out=[];foreach($s->fetchAll() as $r)$out[(string)$r['legacy_id']]=(string)$r['location_id'];return $out;}
    private function ascOffices():array{$sql="SELECT o.id,o.dad_number,o.name_en,o.linked_location_id,l.dad_number asc_dad,l.name_en asc_name FROM office o JOIN office_type ot ON ot.id=o.office_type_id AND ot.system_key='ASC_OFFICE' JOIN location l ON l.id=o.linked_location_id WHERE o.operational_status='ACTIVE' AND o.approval_status='APPROVED'";$out=[];foreach($this->target->query($sql)->fetchAll() as $r)$out[(string)$r['linked_location_id']]=$r;return $out;}
    private function targetOfficers():array{$out=[];foreach($this->target->query('SELECT id,dad_number,name_with_initials,nic FROM officer')->fetchAll() as $r)$out[(string)$r['id']]=$r;return $out;}
    private function currentAssignments():array{$s=$this->target->prepare("SELECT a.officer_id,a.office_id,a.is_primary,o.dad_number office_dad,o.name_en office_name,ot.system_key office_type_key FROM officer_office_assignment a JOIN office o ON o.id=a.office_id JOIN office_type ot ON ot.id=o.office_type_id WHERE a.active=1 AND a.approval_status='APPROVED' AND a.effective_from<=? AND (a.effective_to IS NULL OR a.effective_to>=?)");$s->execute([$this->asOf,$this->asOf]);$out=[];foreach($s->fetchAll() as $r)$out[(string)$r['officer_id']][]=$r;return $out;}
    private function writeReports(array $report):array{$dir=dirname(__DIR__,3).'/storage/reports';if(!is_dir($dir))mkdir($dir,0770,true);$stamp=date('Ymd-His');$json="{$dir}/arpa-office-backfill-dry-run-{$stamp}.json";$csv="{$dir}/arpa-office-backfill-by-asc-{$stamp}.csv";$kur="{$dir}/arpa-office-backfill-kurunegala-{$stamp}.csv";file_put_contents($json,json_encode($report,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));$h=fopen($csv,'wb');fputcsv($h,['asc_dad','asc_name','office_dad','office_name','distinct_officers_proposed']);foreach($report['by_asc'] as $r)fputcsv($h,[$r['asc_dad'],$r['asc_name'],$r['office_dad'],$r['office_name'],$r['distinct_officers']]);fclose($h);$h=fopen($kur,'wb');fputcsv($h,['target_officer_dad','officer_name','nic','legacy_officer_ids','supporting_arpa_divisions','duty_types','legacy_appointment_row_count','resolved_asc','resolved_office','existing_office_assignments','primary_office_status','proposed_action']);foreach($report['kurunegala'] as $r)fputcsv($h,[$r['officer_dad'],$r['officer_name'],$r['nic'],implode('|',$r['legacy_officer_ids']),implode('|',$r['supporting_divisions']),implode('|',$r['duty_types']),$r['supporting_row_count'],$r['asc_dad'].' '.$r['asc_name'],$r['office_dad'].' '.$r['office_name'],implode('|',$r['existing_assignments']),$r['primary_status'],$r['proposed_action']]);fclose($h);return compact('json','csv','kur');}
    private function legacyAscId(array $rows):?string{foreach($rows as $r)if(($v=$this->positive($r['legacy_asc_id']))!==null)return $v;return null;}private function positive(mixed $v):?string{$v=trim((string)$v);return ctype_digit($v)&&(int)$v>0?(string)(int)$v:null;}private function dutyName(mixed $v):string{return match((int)$v){1=>'PERMANENT',2=>'ACTING',3=>'DUTY_COVERING',4=>'ATTEND_TO_DUTY',default=>'UNKNOWN'};}private function assertDate(string $v):void{$d=\DateTimeImmutable::createFromFormat('!Y-m-d',$v);if(!$d||$d->format('Y-m-d')!==$v)throw new RuntimeException('As-of date must be YYYY-MM-DD.');}
    private function sourceState():array{return ['tbl_officer_apoint_2026'=>(int)$this->source->query('SELECT COUNT(*) FROM tbl_officer_apoint_2026')->fetchColumn()];}private function targetState():array{$out=[];foreach(['officer','office','officer_office_assignment','arpa_division_appointment','arpa_subject_assignment','system_user'] as $t)$out[$t]=(int)$this->target->query("SELECT COUNT(*) FROM {$t}")->fetchColumn();return $out;}
}
