<?php use App\Core\Csrf; ?>
<div class="page-heading"><div><div class="breadcrumb-lite">Human Resource Management / Officers / Office Assignment</div><h1>Assign Office</h1><p><?= e($officer['dad_number'].' - '.$officer['name_with_initials']) ?></p></div></div>
<form method="post" action="<?= e(url('hr/officers/'.$officer['id'].'/offices')) ?>" class="card"><div class="card-body"><?= Csrf::field() ?><div class="row g-3">
<?php if(!empty($returnedAssignment)): ?><input type="hidden" name="assignment_id" value="<?= e($returnedAssignment['id']) ?>"><div class="col-12"><div class="alert alert-warning mb-0"><strong>Returned for Correction</strong><br>Correct this same Office Assignment request and resubmit it for approval.</div></div><?php endif; ?>
<div class="col-md-4"><label class="form-label">NIC</label><input class="form-control" value="<?= e($officer['nic']?:'—') ?>" readonly></div>
<div class="col-md-4"><label class="form-label">Designation</label><input class="form-control" value="<?= e($officer['designation_name']?:'—') ?>" readonly></div>
<div class="col-md-4"><label class="form-label">Officer Status</label><input class="form-control" value="<?= e($officer['officer_status_name']?:$officer['operational_status']?:'—') ?>" readonly></div>
<div class="col-12"><label class="form-label">Current Office</label><input class="form-control" value="<?= e($currentOfficeLabel) ?>" readonly></div>
<div class="col-md-8"><label class="form-label" for="office-id">Requested Office *</label><select class="form-select" id="office-id" name="office_id" required><option value="">Select authorized Office</option><?php foreach($offices as $o): ?><option value="<?= e($o['id']) ?>" <?= (string)($returnedAssignment['office_id']??'')===(string)$o['id']?'selected':'' ?>><?= e($o['dad_number'].' - '.$o['name_en'].' ('.$o['office_type'].') — '.($o['location_name']?:'National').($o['district_name']?' / '.$o['district_name']:'')) ?></option><?php endforeach; ?></select><div class="form-text">Only approved, active Offices permitted by the current Active Working Context are listed.</div></div>
<div class="col-md-4"><label class="form-label" for="effective-from">Assignment Start Date *</label><input class="form-control" id="effective-from" type="date" name="effective_from" value="<?= e($returnedAssignment['effective_from']??date('Y-m-d')) ?>" required></div>
<div class="col-md-6"><label class="form-label" for="reason">Reason *</label><input class="form-control" id="reason" name="reason" maxlength="500" value="<?= e($returnedAssignment['reason']??'') ?>" required></div><div class="col-md-6"><label class="form-label" for="official-reference">Official Reference</label><input class="form-control" id="official-reference" name="official_reference" maxlength="255" value="<?= e($returnedAssignment['official_reference']??'') ?>"></div>
<div class="col-12"><label class="form-label" for="remarks">Remarks</label><textarea class="form-control" id="remarks" name="remarks"><?= e($returnedAssignment['remarks']??'') ?></textarea></div><div class="col-12 form-check ms-2"><input class="form-check-input" id="is-primary" type="checkbox" name="is_primary" value="1" <?= !empty($returnedAssignment['is_primary'])?'checked':'' ?>><label class="form-check-label" for="is-primary">Primary Office</label></div>
</div><div class="mt-3"><button class="btn btn-primary"><?= !empty($returnedAssignment)?'Resubmit Office Assignment':'Submit Office Assignment for Approval' ?></button> <a class="btn btn-outline-secondary" href="<?= e(url('hr/officers/'.$officer['id'])) ?>">Cancel</a></div></div></form>
