<?php
declare(strict_types=1);
use App\Core\Database;
use App\Services\NotificationService;
require dirname(__DIR__).'/bootstrap.php';
final class NotificationCenterTest
{
    private PDO $pdo;private int $assertions=0;
    public function run():int{$this->pdo=Database::pdo();$this->pdo->beginTransaction();try{$this->testLifecycle();$this->testCodeContracts();}finally{if($this->pdo->inTransaction())$this->pdo->rollBack();}echo "NotificationCenterTest: {$this->assertions} assertions passed.\n";return 0;}
    private function testLifecycle():void{$users=$this->pdo->query('SELECT id FROM system_user ORDER BY id LIMIT 3')->fetchAll(PDO::FETCH_COLUMN);if(count($users)<3)throw new RuntimeException('Three user identities are required.');[$a,$b,$actor]=array_map('strval',$users);$s=new NotificationService($this->pdo);$id=$s->createActionRequired($a,'TEST','Approval needed','Review this item.','TEST_ENTITY',$actor,'APPROVAL','/notifications');$this->same(1,$s->pendingCount($a),'action required increments pending count');$this->same($id,$s->createActionRequired($a,'TEST','Approval needed','Review this item.','TEST_ENTITY',$actor,'APPROVAL','/notifications'),'duplicate active notification is deduplicated');$s->markRead($id,$a);$row=$s->forUser($id,$a);$this->same('PENDING',$row['action_status'],'mark read does not complete action');$this->same(true,$row['read_at']!==null,'mark read records read_at');$this->throws(fn()=>$s->forUser($id,$b),'user cannot read another recipient notification');$s->createActionRequired($b,'TEST','Approval needed','Review this item.','TEST_ENTITY',$actor,'APPROVAL','/notifications');$s->resolveStage('TEST_ENTITY',$actor,'APPROVAL',$b,'Approved');$this->same('RESOLVED_BY_OTHER',$s->forUser($id,$a)['action_status'],'sibling notification resolves by other');$other=$this->pdo->prepare('SELECT action_status FROM system_notification WHERE recipient_user_id=? AND entity_type=\'TEST_ENTITY\' AND entity_id=?');$other->execute([$b,$actor]);$this->same('COMPLETED',$other->fetchColumn(),'acting recipient notification completes');$this->same(0,$s->pendingCount($a),'completed actions are excluded from pending count');$info=$s->createInformation($a,'TEST','Done','Workflow completed.','TEST_ENTITY',$actor,'/notifications',$b);$this->same('INFORMATION',$s->forUser($info,$a)['notification_type'],'information notification is retained');}
    private function testCodeContracts():void{$controller=file_get_contents(dirname(__DIR__).'/app/Controllers/NotificationController.php');$this->same(true,str_contains($controller,'recipient_user_id')||str_contains(file_get_contents(dirname(__DIR__).'/app/Services/NotificationService.php'),'recipient_user_id=?'),'notification access is recipient-bound');$layout=file_get_contents(dirname(__DIR__).'/app/Views/layouts/admin.php');$this->same(true,str_contains($layout,'bi-bell-fill'),'authenticated header contains notification bell');}
    private function same(mixed $e,mixed $a,string $m):void{$this->assertions++;if($e!==$a)throw new RuntimeException($m.' expected '.var_export($e,true).' got '.var_export($a,true));}private function throws(callable $fn,string $m):void{$this->assertions++;try{$fn();}catch(Throwable){return;}throw new RuntimeException($m);}
}
exit((new NotificationCenterTest())->run());
