<?php
declare(strict_types=1);
use App\Core\Database;
use App\Services\NotificationService;
require dirname(__DIR__).'/bootstrap.php';
final class NotificationCenterTest
{
    private PDO $pdo;private int $assertions=0;
    public function run():int{$this->pdo=Database::pdo();$this->pdo->beginTransaction();try{$this->testLifecycle();$this->testOfficerContext();$this->testCodeContracts();}finally{if($this->pdo->inTransaction())$this->pdo->rollBack();}echo "NotificationCenterTest: {$this->assertions} assertions passed.\n";return 0;}
    private function testLifecycle():void{$users=$this->pdo->query('SELECT id FROM system_user ORDER BY id LIMIT 3')->fetchAll(PDO::FETCH_COLUMN);if(count($users)<3)throw new RuntimeException('Three user identities are required.');[$a,$b,$actor]=array_map('strval',$users);$s=new NotificationService($this->pdo);$id=$s->createActionRequired($a,'TEST','Approval needed','Review this item.','TEST_ENTITY',$actor,'APPROVAL','/notifications');$this->same(1,$s->pendingCount($a),'action required increments pending count');$this->same($id,$s->createActionRequired($a,'TEST','Approval needed','Review this item.','TEST_ENTITY',$actor,'APPROVAL','/notifications'),'duplicate active notification is deduplicated');$s->markRead($id,$a);$row=$s->forUser($id,$a);$this->same('PENDING',$row['action_status'],'mark read does not complete action');$this->same(true,$row['read_at']!==null,'mark read records read_at');$this->throws(fn()=>$s->forUser($id,$b),'user cannot read another recipient notification');$s->createActionRequired($b,'TEST','Approval needed','Review this item.','TEST_ENTITY',$actor,'APPROVAL','/notifications');$s->resolveStage('TEST_ENTITY',$actor,'APPROVAL',$b,'Approved');$this->same('RESOLVED_BY_OTHER',$s->forUser($id,$a)['action_status'],'sibling notification resolves by other');$other=$this->pdo->prepare('SELECT action_status FROM system_notification WHERE recipient_user_id=? AND entity_type=\'TEST_ENTITY\' AND entity_id=?');$other->execute([$b,$actor]);$this->same('COMPLETED',$other->fetchColumn(),'acting recipient notification completes');$this->same(0,$s->pendingCount($a),'completed actions are excluded from pending count');$info=$s->createInformation($a,'TEST','Done','Workflow completed.','TEST_ENTITY',$actor,'/notifications',$b);$this->same('INFORMATION',$s->forUser($info,$a)['notification_type'],'information notification is retained');}
    private function testOfficerContext():void
    {
        $fixture=$this->pdo->query("SELECT a.id assignment_id,f.id officer_id,f.dad_number officer_dad,f.name_with_initials officer_name,o.id office_id,o.dad_number office_dad,o.name_en office_name FROM officer_office_assignment a JOIN officer f ON f.id=a.officer_id JOIN office o ON o.id=a.office_id WHERE a.deleted_at IS NULL ORDER BY a.created_at,a.id LIMIT 1")->fetch();
        if(!$fixture)throw new RuntimeException('An Officer Office Assignment fixture is required.');
        $recipient=(string)$this->pdo->query('SELECT id FROM system_user ORDER BY id LIMIT 1')->fetchColumn();$service=new NotificationService($this->pdo);
        $id=$service->createActionRequired($recipient,'OFFICER','Office assignment review','Review the Officer Office Assignment.','OFFICER_OFFICE_ASSIGNMENT',(string)$fixture['assignment_id'],'APPROVAL','/hr/officers/office-assignments/'.$fixture['assignment_id'].'/review');
        $rows=$service->recent($recipient,20);$row=null;foreach($rows as $candidate)if((string)$candidate['id']===$id){$row=$candidate;break;}
        $this->same(true,is_array($row),'Officer-related recent notification is returned with context');$display=NotificationService::displayContext($row??[]);
        $this->same($fixture['officer_dad'].' - '.$fixture['officer_name'],$display['officer'],'Officer notification displays DAD number and Officer name');
        $this->same($fixture['office_dad'].' - '.$fixture['office_name'],$display['office'],'transaction-specific assigned Office is displayed');
        $visible=implode(' ',array_filter($display));$this->same(false,str_contains($visible,(string)$fixture['officer_id'])||str_contains($visible,(string)$fixture['office_id']),'Officer and Office UUIDs are not presentation text');
        $unassigned=$this->pdo->query("SELECT f.id,f.dad_number,f.name_with_initials FROM officer f WHERE f.primary_office_id IS NULL AND NOT EXISTS(SELECT 1 FROM officer_office_assignment a WHERE a.officer_id=f.id AND a.deleted_at IS NULL) ORDER BY f.id LIMIT 1")->fetch();if(!$unassigned)throw new RuntimeException('An Officer without an Office assignment is required.');
        $missingOfficeId=$service->createActionRequired($recipient,'OFFICER','Officer review','Review the Officer.','OFFICER',(string)$unassigned['id'],'APPROVAL','/hr/officers/'.$unassigned['id']);$missingOfficeRow=null;foreach($service->recent($recipient,20) as $candidate)if((string)$candidate['id']===$missingOfficeId){$missingOfficeRow=$candidate;break;}$missingOffice=NotificationService::displayContext($missingOfficeRow??[]);
        $this->same($unassigned['dad_number'].' - '.$unassigned['name_with_initials'],$missingOffice['officer'],'Officer context remains available when Office cannot be resolved');$this->same(null,$missingOffice['office'],'missing Office is omitted safely');
        $nonOfficerId=$service->createInformation($recipient,'TEST','General notice','No Officer is related.','TEST_ENTITY',$this->uuid(),'/notifications');$nonOfficer=null;foreach($service->recent($recipient,20) as $candidate)if((string)$candidate['id']===$nonOfficerId){$nonOfficer=$candidate;break;}
        $this->same(['officer'=>null,'office'=>null],NotificationService::displayContext($nonOfficer??[]),'non-Officer notification keeps the existing context-free presentation');
        $stored=$service->forUser($id,$recipient);$this->same('/hr/officers/office-assignments/'.$fixture['assignment_id'].'/review',$stored['action_url'],'notification action URL is unchanged by display enrichment');$service->markRead($id,$recipient);$this->same(true,$service->forUser($id,$recipient)['read_at']!==null,'notification read behavior is unchanged');
        $parts=NotificationService::contextQueryParts('n');$this->same(true,str_contains($parts['joins'],'officer_office_assignment')&&str_contains($parts['joins'],'arpa_division_appointment_request'),'collection context is resolved by one set-based query projection rather than per-row service queries');
    }
    private function testCodeContracts():void{$controller=file_get_contents(dirname(__DIR__).'/app/Controllers/NotificationController.php');$this->same(true,str_contains($controller,'recipient_user_id')||str_contains(file_get_contents(dirname(__DIR__).'/app/Services/NotificationService.php'),'recipient_user_id=?'),'notification access is recipient-bound');$layout=file_get_contents(dirname(__DIR__).'/app/Views/layouts/admin.php');$this->same(true,str_contains($layout,'bi-bell-fill'),'authenticated header contains notification bell');$this->same(true,str_contains($layout,'dropdown-menu-end')&&str_contains($layout,'notification-dropdown-list'),'notification dropdown remains right-aligned and uses a dedicated scrollable list with header/footer outside it');$this->same(true,str_contains($layout,'notification-title-row')&&str_contains($layout,'notification-type-badge'),'notification title and badge use the dedicated horizontal layout');$css=file_get_contents(dirname(__DIR__).'/public/assets/css/app.css');$this->same(true,str_contains($css,'width:min(680px,calc(100vw - 32px))')&&str_contains($css,'min-width:560px')&&str_contains($css,'@media(max-width:700px)')&&str_contains($css,'width:calc(100vw - 24px);min-width:0'),'notification dropdown has the required responsive desktop and mobile widths');$this->same(true,str_contains($css,'max-height:min(65vh,600px)')&&str_contains($css,'overflow-y:auto')&&str_contains($css,'overflow-x:hidden')&&str_contains($css,'scrollbar-gutter:stable')&&str_contains($css,'overscroll-behavior:contain'),'notification list has one usable bounded vertical scroll container');$this->same(true,str_contains($css,'.notification-title{flex:1 1 auto;min-width:0}')&&str_contains($css,'.notification-type-badge{flex:0 0 auto;align-self:flex-start;white-space:nowrap}')&&str_contains($css,'overflow-wrap:anywhere'),'notification title wraps while the action badge stays compact');$registry=file_get_contents(dirname(__DIR__).'/app/Core/DataTableRegistry.php');$this->same(true,str_contains($registry,'NotificationService::displayContext'),'full Notification Center uses the shared Officer/Office presentation helper');}
    private function uuid():string{return (string)$this->pdo->query('SELECT UUID()')->fetchColumn();}
    private function same(mixed $e,mixed $a,string $m):void{$this->assertions++;if($e!==$a)throw new RuntimeException($m.' expected '.var_export($e,true).' got '.var_export($a,true));}private function throws(callable $fn,string $m):void{$this->assertions++;try{$fn();}catch(Throwable){return;}throw new RuntimeException($m);}
}
exit((new NotificationCenterTest())->run());
