<?php
declare(strict_types=1);

use App\Core\{Auth,DataTableQuery,DataTableRegistry,DataTableRequest,Database,LegacyDatabase,NicNormalizer,ScopeService};
use App\Services\{OfficerProfileService,UserContextService};
use App\Services\LegacyOfficer\LegacyOfficerPersonnelBackfillService;

require dirname(__DIR__).'/bootstrap.php';

final class OfficerPersonnelProfileTest
{
    private PDO $pdo;private PDO $legacy;private int $assertions=0;
    public function run():int
    {
        $this->pdo=Database::pdo();$this->legacy=LegacyDatabase::pdo();$this->backfill();$this->nicAndScope();$this->profile();$this->appointmentPeriods();$this->safety();echo "OfficerPersonnelProfileTest: {$this->assertions} assertions passed.\n";return 0;
    }
    private function backfill():void
    {
        $before=$this->state();$r=(new LegacyOfficerPersonnelBackfillService($this->legacy,$this->pdo))->dryRun();$this->same(6429,$r['target_officers_examined'],'all target Officers examined');$this->same(6429,$r['target_officers_mapped'],'all Officers mapped by legacy reference');$this->same(0,$r['would_update'],'execute rerun is idempotent');$this->same(0,$r['true_blockers'],'no identity blockers');$this->same(2,$r['permanency_unknown'],'ambiguous Select permanency remains unknown');$this->same(true,$r['alias_field_conflicts']>0,'conflicting alias fields are reported');$this->same($before,$this->state(),'dry-run makes no operational writes');
        $this->same(0,$this->scalar("SELECT COUNT(*) FROM officer o JOIN legacy_officer_reference r ON r.officer_id=o.id JOIN dems_legacy_hr.tbl_officer lo ON lo.officer_id=r.legacy_officer_id WHERE TRIM(lo.permanent_or_not)='Yes' AND o.arpa_service_permanency<>'PERMANENT_IN_SERVICE'"),'Yes maps to permanent in service');$this->same(0,$this->scalar("SELECT COUNT(*) FROM officer o JOIN legacy_officer_reference r ON r.officer_id=o.id JOIN dems_legacy_hr.tbl_officer lo ON lo.officer_id=r.legacy_officer_id WHERE TRIM(lo.permanent_or_not)='No' AND o.arpa_service_permanency<>'NOT_PERMANENT_IN_SERVICE'"),'No maps to not permanent in service');
        $this->same(true,$this->scalar("SELECT COUNT(*) FROM legacy_officer_personnel_issue WHERE issue_type='ALIAS_FIELD_CONFLICT'")>0,'alias conflicts retained in provenance issues');
    }
    private function nicAndScope():void
    {
        $this->same('735190431V',NicNormalizer::normalize(' 735190431v '),'old NIC normalization is case-safe');$this->same('196566110037',NicNormalizer::normalize('196566110037'),'modern NIC normalization supported');$context=$this->pdo->query("SELECT su.id user_id,uar.id role_assignment_id,uas.id scope_assignment_id FROM system_user su JOIN user_account_role uar ON uar.user_id=su.id JOIN application_role r ON r.id=uar.role_id AND r.role_code='ASC_SUBJECT_OFFICER' JOIN user_account_scope uas ON uas.role_assignment_id=uar.id AND uas.user_id=uar.user_id JOIN location l ON l.id=uas.location_id AND l.dad_number='70004-0000389' WHERE su.username='asctest' AND uar.active=1 AND uar.approval_status='APPROVED' AND uas.active=1 AND uas.approval_status='APPROVED' LIMIT 1")->fetch();if(!$context)throw new RuntimeException('asctest ASC Subject Officer context is required.');$user=(string)$context['user_id'];$_SESSION=['user_id'=>$user,'authenticated_at'=>time(),'last_activity_at'=>time()];(new UserContextService($this->pdo))->select($user,(string)$context['role_assignment_id'],(string)$context['scope_assignment_id']);Auth::forgetRequestCache();$access=ScopeService::currentOfficerAccess($user,'o.id');$s=$this->pdo->prepare($access['with']." SELECT o.id,o.nic FROM officer o WHERE ".implode(' AND ',$access['where'])." AND o.nic_normalized=?");$s->execute(array_merge($access['params'],['735190431V']));$visible=$s->fetch();$this->same(true,(bool)$visible,'scoped old-format NIC is searchable');$this->same(true,ScopeService::canAccessOfficer($user,$visible['id']),'own scoped Officer is accessible');$outside=(string)$this->pdo->query("SELECT id FROM officer WHERE id<>'{$visible['id']}' ORDER BY dad_number LIMIT 1")->fetchColumn();$this->same(false,ScopeService::canAccessOfficer($user,$outside),'unrelated Officer direct access rejected');
        $definition=DataTableRegistry::definition('officers');$response=(new DataTableQuery($this->pdo,$definition,new DataTableRequest(['length'=>25,'search'=>['value'=>'735190431v']])))->response();$this->same(1,$response['recordsFiltered'],'DataTable NIC search is scoped and case-insensitive under collation');$this->same(true,in_array('Current Assignments',array_column($definition['columns'],'label'),true),'Officer list exposes current assignments');$searchView=file_get_contents(BASE_PATH.'/app/Views/officers/search.php');$this->contains('method="post"',$searchView,'NIC is never placed in a URL query string');$this->contains('Csrf::field()',$searchView,'NIC search is CSRF protected');$this->contains('Matching Officers',$searchView,'ambiguous NIC results provide a selection list');
    }
    private function profile():void
    {
        $user=(string)$this->pdo->query("SELECT id FROM system_user WHERE username='asctest'")->fetchColumn();$offices=ScopeService::scopedOffices($user);$ascIds=array_column(ScopeService::scopedLocations($user,'ASC'),'id');$officer=(string)$this->pdo->query("SELECT oa.officer_id FROM officer_office_assignment oa JOIN office o ON o.id=oa.office_id WHERE o.id='{$offices[0]['id']}' AND oa.active=1 AND oa.approval_status='APPROVED' LIMIT 1")->fetchColumn();$p=(new OfficerProfileService($this->pdo))->profile($officer,array_column($offices,'id'),$ascIds);$this->same(true,!empty($p['officer']['permanent_address']),'profile includes residential address');$this->same(true,!empty($p['officer']['date_of_birth']),'profile includes DOB');$this->same(true,!empty($p['officer']['initial_appointment_date']),'profile includes first appointment date');$this->same(1,count($p['current_offices']),'current scoped Office displayed');$this->same(0,count($p['legacy_current'])+count($p['legacy_previous']),'migrated profile does not duplicate legacy preview rows');$this->same(4,$this->scalar('SELECT COUNT(*) FROM legacy_arpa_appointment_preview p WHERE p.active=1 AND NOT EXISTS(SELECT 1 FROM legacy_arpa_appointment_business_record br WHERE br.reconciled_business_key=p.reconciled_business_key)'),'only four manual-review previews remain globally');
        $view=file_get_contents(BASE_PATH.'/app/Views/officers/show.php');foreach(['Personal Information','Service Information','Current Office','Current ARPA Assignments','Scheduled / Future ARPA Assignments','ARPA Assignment History','Current ASC Subject / Function Assignments','Legacy Appointment History - Not Yet Migrated','LEGACY / NOT YET MIGRATED','Title','Civil Status','WhatsApp Number'] as $label)$this->contains($label,$view,"profile displays {$label}");$service=file_get_contents(BASE_PATH.'/app/Services/OfficerProfileService.php');$this->contains('legacy_arpa_appointment_business_record',$service,'every migrated envelope suppresses its duplicate preview record');$this->contains("workflow_status='NATIONAL_APPROVED'",$service,'only finally approved operational appointment may be current');$this->contains("THEN 'FUTURE'",$service,'future appointment has a separate profile period');
    }
    private function appointmentPeriods():void
    {
        $user=(string)$this->pdo->query("SELECT id FROM system_user WHERE username='asctest'")->fetchColumn();$offices=ScopeService::scopedOffices($user);$ascIds=array_column(ScopeService::scopedLocations($user,'ASC'),'id');$officer=(string)$this->pdo->query("SELECT officer_id FROM officer_office_assignment WHERE office_id='{$offices[0]['id']}' AND active=1 AND approval_status='APPROVED' LIMIT 1")->fetchColumn();$marks=implode(',',array_fill(0,count($ascIds),'?'));$s=$this->pdo->prepare("SELECT p.asc_location_id,p.arpa_location_id,a.dad_number asc_dad,a.name_en asc_name,r.dad_number arpa_dad,r.name_en arpa_name FROM legacy_arpa_appointment_preview p JOIN location a ON a.id=p.asc_location_id JOIN location r ON r.id=p.arpa_location_id WHERE p.officer_id=? AND p.asc_location_id IN ({$marks}) AND p.arpa_location_id IS NOT NULL LIMIT 1");$s->execute(array_merge([$officer],$ascIds));$location=$s->fetch();if(!$location)return;
        $permanency=(string)$this->pdo->query("SELECT arpa_service_permanency FROM officer WHERE id='{$officer}'")->fetchColumn();$endReason=(string)$this->pdo->query("SELECT id FROM arpa_appointment_end_reason WHERE active=1 ORDER BY display_order,id LIMIT 1")->fetchColumn();if($permanency===''||$endReason==='')return;$this->pdo->beginTransaction();try{$rows=[['CURRENT',date('Y-m-d',strtotime('-30 days')),null],['FUTURE',date('Y-m-d',strtotime('+30 days')),null],['PREVIOUS',date('Y-m-d',strtotime('-90 days')),date('Y-m-d',strtotime('-10 days'))]];foreach($rows as [$period,$from,$to]){$request=(string)$this->pdo->query('SELECT UUID()')->fetchColumn();$appointment=(string)$this->pdo->query('SELECT UUID()')->fetchColumn();$this->pdo->prepare("INSERT INTO arpa_division_appointment_request(id,request_type,officer_id,appointment_type,asc_location_id,arpa_division_location_id,requested_effective_from,workflow_status,created_by) VALUES(?,'APPOINTMENT',?,'ACTING',?,?,?,'NATIONAL_APPROVED',?)")->execute([$request,$officer,$location['asc_location_id'],$location['arpa_location_id'],$from,$user]);$this->pdo->prepare("INSERT INTO arpa_division_appointment(id,request_id,officer_id,appointment_type,service_permanency_snapshot,asc_location_id,arpa_division_location_id,asc_dad_snapshot,asc_name_snapshot,arpa_dad_snapshot,arpa_name_snapshot,hierarchy_snapshot_json,effective_from,approved_by,approved_at) VALUES(?,?,?,'ACTING',?,?,?,?,?,? ,?,'{}',?,?,NOW())")->execute([$appointment,$request,$officer,$permanency,$location['asc_location_id'],$location['arpa_location_id'],$location['asc_dad'],$location['asc_name'],$location['arpa_dad'],$location['arpa_name'],$from,$user]);if($to!==null)$this->pdo->prepare("INSERT INTO arpa_division_appointment_closure(id,appointment_id,request_id,effective_to,end_reason_id,closure_kind,context_snapshot_json,approved_by,approved_at) VALUES(UUID(),?,?,?,?,'END','{}',?,NOW())")->execute([$appointment,$request,$to,$endReason,$user]);}
            $profile=(new OfficerProfileService($this->pdo))->profile($officer,array_column($offices,'id'),$ascIds);$this->same(1,count(array_filter($profile['current_appointments'],fn($r)=>$r['record_origin']==='NATIVE')),'current appointment remains current');$this->same(1,count(array_filter($profile['future_appointments'],fn($r)=>$r['record_origin']==='NATIVE')),'future appointment is scheduled');$this->same(1,count(array_filter($profile['previous_appointments'],fn($r)=>$r['record_origin']==='NATIVE')),'ended appointment is historical');
        }finally{$this->pdo->rollBack();}
    }
    private function safety():void{$this->same(5192,$this->scalar("SELECT COUNT(*) FROM officer_office_assignment WHERE record_origin='LEGACY_CURRENT_STATE_BACKFILL'"),'Office assignments unchanged');$this->same(0,$this->scalar("SELECT COUNT(*) FROM arpa_division_appointment WHERE record_origin='NATIVE'"),'legacy migration creates no native appointments');$this->same(0,$this->scalar("SELECT COUNT(*) FROM system_user WHERE identity_type='HISTORICAL' AND enabled=1"),'historical users remain disabled');}
    private function state():array{return ['offices'=>$this->scalar('SELECT COUNT(*) FROM officer_office_assignment'),'appointments'=>$this->scalar('SELECT COUNT(*) FROM arpa_division_appointment'),'subjects'=>$this->scalar('SELECT COUNT(*) FROM arpa_subject_assignment'),'users'=>$this->scalar("SELECT COUNT(*) FROM system_user WHERE identity_type='HISTORICAL' AND enabled=1")];}
    private function scalar(string $sql):int{return (int)$this->pdo->query($sql)->fetchColumn();}private function same(mixed $e,mixed $a,string $m):void{$this->assertions++;if($e!==$a)throw new RuntimeException("{$m}: expected ".var_export($e,true).', got '.var_export($a,true));}private function contains(string $n,string $h,string $m):void{$this->assertions++;if(!str_contains($h,$n))throw new RuntimeException("{$m}: missing {$n}");}
}
exit((new OfficerPersonnelProfileTest())->run());
