<?php
use App\Core\{Csrf,SecurityHeaders};

$byLevel=[];
foreach($roles as $role)$byLevel[$role['role_level']][]=$role;
$levelLabels=['FARMER'=>'Farmer','ARPA'=>'ARPA Division','ASC'=>'Agrarian Service Center','DISTRICT'=>'District','NATIONAL'=>'National Level'];
?>
<div class="page-heading"><div><div class="breadcrumb-lite">User Management / Inactive Users / Activate</div><h1>Activate User</h1><p>Give this user a new DEMS password, role, and assigned location. Old access is not copied automatically.</p></div></div>
<div class="row g-3"><div class="col-xl-5"><div class="form-section"><h2 class="h5">Historical identity</h2><dl class="row mb-0"><dt class="col-sm-5">Legacy User ID</dt><dd class="col-sm-7"><code><?= e($identity['legacy_user_id']) ?></code></dd><dt class="col-sm-5">Current Username</dt><dd class="col-sm-7"><?= e($identity['username']) ?></dd><dt class="col-sm-5">Display Name</dt><dd class="col-sm-7"><?= e($identity['display_name']?:$identity['legacy_display_name']) ?></dd><dt class="col-sm-5">NIC</dt><dd class="col-sm-7"><?= e($identity['legacy_nic']?:'Unavailable') ?></dd><dt class="col-sm-5">Legacy Role</dt><dd class="col-sm-7"><?= e($identity['legacy_role_name']?:'Unavailable') ?></dd><dt class="col-sm-5">Legacy Level</dt><dd class="col-sm-7"><?= e($identity['legacy_user_level_name']?:'Unavailable') ?></dd><dt class="col-sm-5">Workflow Activity</dt><dd class="col-sm-7"><?= e((string)$identity['workflow_activity_count']) ?> reconciled records</dd></dl></div>
<div class="form-section mt-3"><h2 class="h5">Legacy organizational evidence</h2><?php if(!$legacyContexts): ?><p class="text-muted mb-0">No legacy organizational mapping was preserved.</p><?php else: ?><ul class="mb-0"><?php foreach($legacyContexts as $context): ?><li><?= e($context['legacy_level_key'].' - '.trim((string)$context['dad_number'].' '.(string)$context['name_en']).' (legacy '.$context['legacy_location_id'].')') ?></li><?php endforeach; ?></ul><?php endif; ?></div></div>
<div class="col-xl-7"><form class="form-section" method="post" action="<?= e(url('access-management/users/'.$identity['id'].'/activate')) ?>"><?= Csrf::field() ?><h2 class="h5">Current Access</h2><div class="alert alert-warning">The user, password, roles, and assigned locations will be activated together.</div>
<input type="hidden" name="identity_type" value="STAFF"><div class="row g-3"><div class="col-md-6"><label class="form-label">Username *</label><input class="form-control" name="username" value="<?= e($identity['username']) ?>" minlength="5" maxlength="50" required><div class="form-text">Enter the username this person will use to sign in.</div></div><div class="col-md-6"><label class="form-label">Email</label><input type="email" class="form-control" name="email"><div class="form-text">Enter the user's current email address.</div></div><div class="col-md-6"><label class="form-label">Temporary Password *</label><input type="password" class="form-control" name="temporary_password" minlength="8" required><div class="form-text">Use uppercase and lowercase letters, a number, and a symbol. The user must change this password after signing in.</div></div><div class="col-md-6"><label class="form-label">Start Date *</label><input type="date" class="form-control" name="effective_from" value="<?= e(date('Y-m-d')) ?>" required></div></div>
<hr><h3 class="h6">Roles and Assigned Locations *</h3><p class="text-muted small">Select one or more roles. Select the correct location where required.</p>
<?php foreach(['FARMER','ARPA','ASC','DISTRICT','NATIONAL'] as $level): if(($byLevel[$level]??[])===[])continue; ?>
<div class="border rounded p-3 mb-3"><strong><?= e($levelLabels[$level]) ?></strong>
<?php foreach($byLevel[$level] as $role): ?><div class="row align-items-center g-2 mt-1 access-role-row" data-role-id="<?= e($role['id']) ?>"><div class="col-md-5"><div class="form-check"><input class="form-check-input access-role-check" type="checkbox" name="role_enabled[]" value="<?= e($role['role_code']) ?>" id="role-<?= e($role['role_code']) ?>"><label class="form-check-label" for="role-<?= e($role['role_code']) ?>"><?= e($role['role_name']) ?></label></div></div><div class="col-md-7"><?php if($level==='NATIONAL'): ?><input type="hidden" name="roles[<?= e($role['role_code']) ?>]" value=""><span class="badge bg-secondary">National Level</span><?php else: ?><input class="form-control form-control-sm access-location-search mb-1" type="search" placeholder="Search <?= e($level==='FARMER'?'Agrarian Service Center':$levelLabels[$level]) ?>" disabled><select class="form-select form-select-sm access-location" name="roles[<?= e($role['role_code']) ?>]" disabled><option value="">Select <?= e($level==='FARMER'?'Agrarian Service Center':$levelLabels[$level]) ?></option></select><?php endif; ?></div></div><?php endforeach; ?></div>
<?php endforeach; ?>
<div class="mb-3"><label class="form-label">Reason *</label><textarea class="form-control" name="reason" rows="3" required></textarea></div><div class="mb-3"><label class="form-label">Reference</label><input class="form-control" name="official_reference"></div><button class="btn btn-primary">Activate User</button> <a class="btn btn-outline-secondary" href="<?= e(url('access-management/users/historical')) ?>">Cancel</a></form></div></div>
<script data-cfasync="false" nonce="<?= e(SecurityHeaders::nonce()) ?>">(()=>{const endpoint=<?= json_encode(url('access-management/assignment-locations'),JSON_THROW_ON_ERROR) ?>;for(const row of document.querySelectorAll('.access-role-row')){const check=row.querySelector('.access-role-check'),search=row.querySelector('.access-location-search'),select=row.querySelector('.access-location');if(!check)continue;let timer=0,request=null;const load=async()=>{if(!select||!check.checked)return;request?.abort();request=new AbortController();select.replaceChildren(new Option('Loading locations...',''));try{const query=new URLSearchParams({role_id:row.dataset.roleId,q:search?.value.trim()||'',limit:'100'}),response=await fetch(endpoint+'?'+query,{headers:{Accept:'application/json'},signal:request.signal});if(!response.ok)throw new Error('Location lookup denied');const data=await response.json();select.replaceChildren(new Option(data.results.length?'Select location':'No matching locations',''));for(const item of data.results)select.add(new Option([item.dad_number,item.name_en].filter(Boolean).join(' - '),item.id));}catch(error){if(error.name!=='AbortError')select.replaceChildren(new Option('Unable to load locations',''));}};check.addEventListener('change',()=>{if(select)select.disabled=!check.checked;if(search)search.disabled=!check.checked;if(check.checked)load();});search?.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(load,250);});}document.querySelector('form')?.addEventListener('submit',function(){const enabled=new Set([...this.querySelectorAll('[name="role_enabled[]"]:checked')].map(x=>x.value));this.querySelectorAll('[name^="roles["]').forEach(field=>{if(!enabled.has(field.name.slice(6,-1)))field.disabled=true});});})();</script>
