<?php use App\Core\{Csrf,SecurityHeaders}; ?>
<div class="page-heading"><div><div class="breadcrumb-lite">User Management / User Roles</div><h1>User Roles</h1><p>View each user's role, assigned location, and active dates.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#assignRole"><i class="bi bi-plus-lg"></i> Add Role</button></div>
<section class="mb-4" aria-labelledby="assignments-by-role"><h2 class="h5" id="assignments-by-role">Users by Role</h2>
<?php if(!$roleGroups): ?><div class="alert alert-info">No user roles are available for your current access.</div><?php endif; ?>
<?php foreach($roleGroups as $roleCode=>$group): ?><div class="form-section mb-3"><div class="d-flex flex-wrap align-items-center justify-content-between gap-2 mb-2"><h3 class="h6 mb-0"><?= e($group['role_name']) ?></h3><span class="badge text-bg-secondary"><?= e(ucwords(strtolower($group['role_level']))) ?> Level</span></div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Name</th><th>Username</th><th>Assigned Location</th><th>Start Date</th><th>End Date</th><th>Status</th><th>Approval</th></tr></thead><tbody><?php foreach($group['assignments'] as $assignment): ?><tr><td><?= e($assignment['display_name']?:'Not set') ?></td><td><?= e($assignment['username']) ?></td><td><?= e($assignment['assigned_location']?:'National Level') ?></td><td><?= e($assignment['effective_from']) ?></td><td><?= e($assignment['effective_to']?:'Current') ?></td><td><span class="badge <?= $assignment['active']?'text-bg-success':'text-bg-secondary' ?>"><?= $assignment['active']?'Active':'Inactive' ?></span></td><td><?= e(ucwords(strtolower(str_replace('_',' ',$assignment['approval_status'])))) ?></td></tr><?php endforeach; ?></tbody></table></div></div><?php endforeach; ?>
</section><h2 class="h5">Role History and Actions</h2>
<?php require BASE_PATH . '/app/Views/components/datatable.php'; ?>
<div class="modal fade" id="assignRole" tabindex="-1"><div class="modal-dialog modal-lg"><form class="modal-content" method="post" action="<?= e(url('access-management/role-assignments')) ?>">
    <?= Csrf::field() ?>
    <div class="modal-header"><h5 class="modal-title"><?= $replacement?'Transfer or Change Role':'Add User Role' ?></h5><button class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div>
    <div class="modal-body">
        <?php if($replacement): ?><input type="hidden" name="user_id" value="<?= e($replacement['user_id']) ?>"><input type="hidden" name="replaces_assignment_id" value="<?= e($replacement['id']) ?>"><div class="alert alert-warning">You are replacing <?= e($replacement['role_name'].' for '.($replacement['display_name']?:$replacement['username'])) ?>. The current role will end after another authorized administrator approves the change.</div><?php else: ?><div class="mb-3"><label class="form-label">User</label><select class="form-select" name="user_id" required><option value="">Select</option><?php foreach ($users as $user): ?><option value="<?= e($user['id']) ?>"><?= e($user['username']) ?></option><?php endforeach; ?></select></div><?php endif; ?>
        <div class="mb-3"><label class="form-label">Role</label><select class="form-select" name="role_id" id="assignment-role" required><option value="">Select</option><?php foreach ($roles as $role): ?><option value="<?= e($role['id']) ?>" data-level="<?= e($role['role_level']) ?>"><?= e($role['role_name']) ?></option><?php endforeach; ?></select></div>
        <div class="mb-3" id="assignment-location-wrap"><label class="form-label" for="assignment-location-search">Office or Location</label><input class="form-control form-control-sm mb-1" type="search" id="assignment-location-search" placeholder="Search by DAD number, name, or official code" autocomplete="off"><select class="form-select" name="location_id" id="assignment-location"><option value="">Select a role first</option></select><div class="form-text">Select the office or location for this role.</div></div>
        <div class="row g-2"><div class="col"><label class="form-label">Start Date</label><input type="date" name="effective_from" class="form-control" value="<?= date('Y-m-d') ?>"></div><div class="col"><label class="form-label">End Date</label><input type="date" name="effective_to" class="form-control"></div></div>
        <div class="row g-2 mt-1"><div class="col-md-8"><label class="form-label">Reason *</label><input class="form-control" name="reason" required></div><div class="col-md-4"><label class="form-label">Reference</label><input class="form-control" name="official_reference"></div></div>
        <div class="alert alert-info mt-3 mb-0">The new role will be submitted for approval.</div>
    </div>
    <div class="modal-footer"><button class="btn btn-primary">Submit</button></div>
</form></div></div>
<script nonce="<?= e(SecurityHeaders::nonce()) ?>">(()=>{const role=document.getElementById('assignment-role'),location=document.getElementById('assignment-location'),search=document.getElementById('assignment-location-search'),wrap=document.getElementById('assignment-location-wrap');if(!role||!location||!search||!wrap)return;const endpoint=<?= json_encode(url('access-management/assignment-locations'),JSON_THROW_ON_ERROR) ?>,geographic=new Set(['DISTRICT','ASC','ARPA']);let timer=0,request=null;const clear=(label)=>{location.replaceChildren(new Option(label,''));};const load=async()=>{const level=role.selectedOptions[0]?.dataset.level||'',roleId=role.value;wrap.hidden=!geographic.has(level);location.required=geographic.has(level);search.required=false;if(!geographic.has(level)||!roleId){clear('National / No location');return;}request?.abort();request=new AbortController();clear('Loading locations...');try{const query=new URLSearchParams({role_id:roleId,q:search.value.trim(),limit:'100'}),response=await fetch(endpoint+'?'+query,{headers:{Accept:'application/json'},signal:request.signal});if(!response.ok)throw new Error('Location lookup denied');const data=await response.json();clear(data.results.length?'Select location':'No matching locations');for(const row of data.results)location.add(new Option([row.location_type,row.dad_number,row.name_en].filter(Boolean).join(' | '),row.id));}catch(error){if(error.name!=='AbortError')clear('Unable to load locations');}};role.addEventListener('change',()=>{search.value='';load();});search.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(load,250);});load();<?php if($replacement): ?>bootstrap.Modal.getOrCreateInstance(document.getElementById('assignRole')).show();<?php endif; ?>})();</script>
