<?php use App\Core\{Csrf,SecurityHeaders}; ?>
<div class="page-heading"><div><div class="breadcrumb-lite">User Management / Assigned Locations</div><h1>Assigned Locations</h1><p>View and manage the location assigned to each approved user role.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#assignScope"><i class="bi bi-plus-lg"></i> Assign Location</button></div>
<?php require BASE_PATH . '/app/Views/components/datatable.php'; ?>
<div class="modal fade" id="assignScope" tabindex="-1"><div class="modal-dialog modal-lg"><form class="modal-content" method="post" action="<?= e(url('access-management/scope-assignments')) ?>">
    <?= Csrf::field() ?>
    <div class="modal-header"><h5 class="modal-title">Assign Location</h5><button class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div>
    <div class="modal-body">
        <div class="row g-3">
            <div class="col-12"><label class="form-label">Approved User Role *</label><select class="form-select" name="role_assignment_id" id="scope-role-assignment" required><option value="">Select</option><?php foreach ($roleAssignments as $assignment): ?><option value="<?= e($assignment['id']) ?>" data-role-id="<?= e($assignment['role_id']) ?>" data-level="<?= e($assignment['role_level']) ?>"><?= e($assignment['username'] . ' - ' . $assignment['role_name']) ?></option><?php endforeach; ?></select></div>
            <div class="col-md-6"><label class="form-label">Access</label><input class="form-control" id="scope-rule" value="Select a user role" readonly></div>
            <div class="col-md-6"><label class="form-label">Start Date</label><input type="date" class="form-control" name="effective_from" value="<?= date('Y-m-d') ?>"></div>
            <div class="col-12" id="scope-location-wrap"><label class="form-label" for="scope-location-search">Office or Location</label><input class="form-control form-control-sm mb-1" type="search" id="scope-location-search" placeholder="Search by DAD number, name, or official code" autocomplete="off"><select class="form-select" name="location_id" id="scope-location"><option value="">Select a user role first</option></select><div class="form-text">Select the office or location for this role.</div></div>
            <div class="col-md-6"><label class="form-label">End Date</label><input type="date" class="form-control" name="effective_to"></div>
        </div>
        <div class="alert alert-info mt-3 mb-0">The assigned location must match the selected role. An ARPA Officer may have more than one ARPA Division.</div>
    </div>
    <div class="modal-footer"><button class="btn btn-primary">Submit</button></div>
</form></div></div>
<script nonce="<?= e(SecurityHeaders::nonce()) ?>">(()=>{const assignment=document.getElementById('scope-role-assignment'),location=document.getElementById('scope-location'),search=document.getElementById('scope-location-search'),wrap=document.getElementById('scope-location-wrap'),rule=document.getElementById('scope-rule');if(!assignment||!location||!search||!wrap||!rule)return;const endpoint=<?= json_encode(url('access-management/assignment-locations'),JSON_THROW_ON_ERROR) ?>,types={DISTRICT:'District',ASC:'Agrarian Service Center',ARPA:'ARPA Division'},modes={DISTRICT:'Includes offices under this District',ASC:'Access for this office',ARPA:'Access for this ARPA Division'};let timer=0,request=null;const clear=(label)=>location.replaceChildren(new Option(label,''));const load=async()=>{const option=assignment.selectedOptions[0],level=option?.dataset.level||'',roleId=option?.dataset.roleId||'',type=types[level]||'';rule.value=type?type+' - '+modes[level]:'National Level';wrap.hidden=type==='';location.required=type!=='';if(type===''||!roleId){clear('National Level');return;}request?.abort();request=new AbortController();clear('Loading locations...');try{const query=new URLSearchParams({role_id:roleId,q:search.value.trim(),limit:'100'}),response=await fetch(endpoint+'?'+query,{headers:{Accept:'application/json'},signal:request.signal});if(!response.ok)throw new Error('Location lookup denied');const data=await response.json();clear(data.results.length?'Select location':'No matching locations');for(const row of data.results)location.add(new Option([row.location_type,row.dad_number,row.name_en].filter(Boolean).join(' | '),row.id));}catch(error){if(error.name!=='AbortError')clear('Unable to load locations');}};assignment.addEventListener('change',()=>{search.value='';load();});search.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(load,250);});load();})();</script>
