<?php use App\Core\{Csrf,DataTableFormat}; ?>
<div class="page-heading">
  <div><div class="breadcrumb-lite">Human Resource Management / Officers / Edit Requests</div><h1>Review Officer Profile Edit</h1><p><?= e($request['dad_number'].' - '.$request['name_with_initials']) ?></p></div>
  <a class="btn btn-outline-secondary" href="<?= e(url('hr/officer-edit-requests')) ?>">Back to Requests</a>
</div>
<div class="row g-3 mb-4">
  <div class="col-lg-6"><div class="card h-100"><div class="card-body"><h2 class="h5">Officer</h2><dl class="row mb-0"><dt class="col-5">DAD Number</dt><dd class="col-7"><?= e($request['dad_number']) ?></dd><dt class="col-5">Name</dt><dd class="col-7"><?= e($request['name_with_initials']) ?></dd><dt class="col-5">NIC</dt><dd class="col-7"><?= e($request['nic']) ?></dd><dt class="col-5">Current Office</dt><dd class="col-7"><?= !empty($request['office_name'])?e(trim(($request['office_dad']??'').' - '.$request['office_name'],' -')):'—' ?></dd></dl></div></div></div>
  <div class="col-lg-6"><div class="card h-100"><div class="card-body"><h2 class="h5">Request</h2><dl class="row mb-0"><dt class="col-5">Requested By</dt><dd class="col-7"><?= e($request['submitted_by_name']?:$request['submitted_by_username']) ?></dd><dt class="col-5">Approval Level</dt><dd class="col-7"><?= e(ucfirst(strtolower($request['request_level']))) ?></dd><dt class="col-5">Submitted</dt><dd class="col-7"><?= e($request['submitted_at']) ?></dd><dt class="col-5">Status</dt><dd class="col-7"><?= DataTableFormat::badge($request['workflow_status']) ?></dd></dl></div></div></div>
</div>
<div class="card mb-4"><div class="card-body"><h2 class="h5">Proposed Changes</h2><div class="table-responsive"><table class="table table-bordered align-middle mb-0"><thead><tr><th>Field</th><th>Current at Submission</th><th>Proposed</th></tr></thead><tbody><?php foreach($request['changes'] as $change): ?><tr class="table-warning"><th><?= e($change['label']) ?></th><td class="text-break"><?= nl2br(e($change['current'])) ?></td><td class="text-break fw-semibold"><?= nl2br(e($change['proposed'])) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php if(!empty($request['can_decide'])): ?>
<div class="row g-3">
  <div class="col-lg-4"><form method="post" action="<?= e(url('hr/officer-edit-requests/'.$request['id'].'/approve')) ?>" class="card h-100"><div class="card-body"><?= Csrf::field() ?><h2 class="h5">Approve</h2><p class="text-muted">Apply only these proposed fields to the Officer master.</p><button class="btn btn-success" type="submit">Approve Changes</button></div></form></div>
  <div class="col-lg-4"><form method="post" action="<?= e(url('hr/officer-edit-requests/'.$request['id'].'/return')) ?>" class="card h-100"><div class="card-body"><?= Csrf::field() ?><h2 class="h5">Return</h2><label class="form-label" for="return_reason">Correction reason</label><textarea class="form-control mb-3" id="return_reason" name="reason" maxlength="1000" required></textarea><button class="btn btn-warning" type="submit">Return for Correction</button></div></form></div>
  <div class="col-lg-4"><form method="post" action="<?= e(url('hr/officer-edit-requests/'.$request['id'].'/reject')) ?>" class="card h-100"><div class="card-body"><?= Csrf::field() ?><h2 class="h5">Reject</h2><label class="form-label" for="rejection_reason">Rejection reason</label><textarea class="form-control mb-3" id="rejection_reason" name="reason" maxlength="1000" required></textarea><button class="btn btn-outline-danger" type="submit">Reject Request</button></div></form></div>
</div>
<?php else: ?><div class="alert alert-secondary">This request is not awaiting a decision from the current user.</div><?php endif; ?>
