<?php use App\Core\Auth; require BASE_PATH.'/app/Views/arpa_appointments/tabs.php'; ?>
<div class="page-heading"><div><div class="breadcrumb-lite">Human Resource Management / ARPA Officer Assignments</div><h1>ARPA Officer Assignments</h1><p>View ARPA Division and Agrarian Service Center subject assignments.</p></div></div>
<div class="row g-3 mb-4">
<?php foreach([['Current Permanent',$stats['openPermanent'],'primary'],['Current Acting',$stats['openActing'],'info'],['Current Duty Covering',$stats['openDutyCovering'],'success'],['Current Attend to the Duty',$stats['openAttendToDuty'],'warning'],['Current Subject Assignments',$stats['openSubjects'],'primary'],['Submitted / Pending',$stats['pending'],'warning'],['Vacant ARPA Divisions',$stats['vacantDivisions'],'secondary'],['Appointment Data Issues',$stats['issues'],'danger']] as $s): ?>
<div class="col-sm-6 col-xl-3"><div class="stat-card h-100"><div class="text-muted small"><?= e($s[0]) ?></div><div class="display-6 fw-semibold text-<?= e($s[2]) ?>"><?= (int)$s[1] ?></div></div></div>
<?php endforeach; ?>
</div>
<div class="row g-3 mb-4">
<div class="col-lg-6"><div class="form-section h-100"><h2 class="h5">Current Assignments by Type</h2><canvas class="dems-chart" data-chart-type="doughnut" data-chart-source="arpa-appointment-mix"></canvas><p class="dems-chart-empty text-muted" hidden>No current assignments.</p><script nonce="<?= e(App\Core\SecurityHeaders::nonce()) ?>" type="application/json" id="arpa-appointment-mix"><?= json_encode($stats['appointmentMix'],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script></div></div>
<div class="col-lg-6"><div class="form-section h-100"><h2 class="h5">ARPA Division Coverage</h2><canvas class="dems-chart" data-chart-type="horizontalBar" data-chart-source="arpa-division-coverage"></canvas><p class="dems-chart-empty text-muted" hidden>No ARPA Divisions are available for your current access.</p><script nonce="<?= e(App\Core\SecurityHeaders::nonce()) ?>" type="application/json" id="arpa-division-coverage"><?= json_encode($stats['divisionCoverage'],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script></div></div>
</div>
<div class="row g-3">
<div class="col-lg-6"><div class="form-section h-100"><h2 class="h5">ARPA Division Assignments</h2><p class="text-muted">Permanent, Acting, Duty Covering, Attend to the Duty, transfers, removals, and assignment history.</p><div class="d-flex gap-2 flex-wrap"><a class="btn btn-outline-primary" href="<?= e(url('hr/arpa-appointments/divisions')) ?>">Current Assignments</a><?php if(Auth::can('arpa.appointment.create')): ?><a class="btn btn-primary" href="<?= e(url('hr/arpa-appointments/new')) ?>">New Assignment</a><?php endif; ?><a class="btn btn-outline-secondary" href="<?= e(url('hr/arpa-appointments/history')) ?>">Assignment History</a></div></div></div>
<div class="col-lg-6"><div class="form-section h-100"><h2 class="h5">ASC Subject Assignments</h2><p class="text-muted">Normal subjects and officer-exclusive Agrarian Bank, Sales Shop, and Sithamu functions.</p><div class="d-flex gap-2 flex-wrap"><a class="btn btn-outline-primary" href="<?= e(url('hr/arpa-appointments/subjects')) ?>">Subject Assignments</a><?php if(Auth::can('arpa.subject.create')): ?><a class="btn btn-primary" href="<?= e(url('hr/arpa-appointments/subjects/create')) ?>">New Subject Assignment</a><?php endif; ?><?php if(Auth::can('subject.master.view')): ?><a class="btn btn-outline-secondary" href="<?= e(url('subjects')) ?>">Head Office Subject Master</a><?php endif; ?></div></div></div>
<div class="col-12"><div class="form-section"><h2 class="h5">Review Progress</h2><p class="text-muted">Assignments move from Agrarian Service Center review to District review and then National approval.</p><a class="btn btn-warning" href="<?= e(url('hr/arpa-appointments/approval')) ?>">Review &amp; Approve</a></div></div>
</div>
