<?php use App\Core\Csrf; require BASE_PATH.'/app/Views/arpa_appointments/tabs.php'; ?>
<div class="page-heading"><div><div class="breadcrumb-lite">ARPA Officer Appointments / Division / New</div><h1>New ARPA Division Appointment</h1><p>This creates a workflow request. It does not become operational until National approval.</p></div></div>
<div class="alert alert-info">An officer must have service permanency recorded and an active Permanent ARPA Division before Acting, Duty Covering, or Attend to the Duty can be requested.</div>
<form method="get" action="<?= e(url('hr/arpa-appointments/divisions/create')) ?>" class="form-section mb-3"><h2 class="h5">1. Select appointment context</h2><div class="row g-3 align-items-end">
<div class="col-lg-6"><label class="form-label" for="context_asc">ASC *</label><select class="form-select" id="context_asc" name="asc_location_id" required><option value="">Select ASC</option><?php foreach($ascs as $r): ?><option value="<?= e($r['id']) ?>" <?= $selectedAsc===$r['id']?'selected':'' ?>><?= e($r['dad_number'].' - '.$r['name_en']) ?></option><?php endforeach; ?></select></div>
<div class="col-lg-3"><label class="form-label" for="context_date">Effective From *</label><input class="form-control" id="context_date" name="effective_from" type="date" value="<?= e($effectiveDate) ?>" required></div>
<div class="col-lg-3"><button class="btn btn-outline-primary w-100">Load Eligible Officers and Vacancies</button></div></div></form>
<?php if($selectedAsc===''): ?><div class="alert alert-secondary">Select an ASC and effective date to load only its eligible ARPA Officers and vacant ARPA Divisions.</div><?php else: ?>
<form method="post" action="<?= e(url('hr/arpa-appointments/divisions')) ?>"><?= Csrf::field() ?><div class="form-section"><h2 class="h5">2. Appointment request</h2><div class="row g-3">
<div class="col-lg-6"><label class="form-label" for="officer_id">Eligible ARPA Officer *</label><select class="form-select" id="officer_id" name="officer_id" required><option value="">Select officer</option><?php foreach($officers as $r): ?><option value="<?= e($r['id']) ?>"><?= e($r['dad_number'].' - '.($r['name_with_initials']?:'Unnamed').' ['.($r['arpa_service_permanency']?:'Permanency not set').']') ?></option><?php endforeach; ?></select><div class="form-text">Only active ARPA Officers with an approved assignment to this ASC Office are available.</div></div>
<div class="col-lg-3"><label class="form-label" for="appointment_type">Appointment Type *</label><select class="form-select" id="appointment_type" name="appointment_type" required><option value="">Select</option><option value="PERMANENT">Permanent</option><option value="ACTING">Acting</option><option value="DUTY_COVERING">Duty Covering</option><option value="ATTEND_TO_DUTY">Attend to the Duty</option></select></div>
<div class="col-lg-3"><label class="form-label" for="effective_from">Effective From *</label><input class="form-control" type="date" id="effective_from" name="effective_from" value="<?= e($effectiveDate) ?>" readonly required></div>
<div class="col-lg-6"><label class="form-label">ASC *</label><?php $ascRow=current(array_filter($ascs,fn($row)=>$row['id']===$selectedAsc))?:null; ?><input class="form-control" value="<?= e($ascRow?($ascRow['dad_number'].' - '.$ascRow['name_en']):$selectedAsc) ?>" readonly><input type="hidden" name="asc_location_id" value="<?= e($selectedAsc) ?>"></div>
<div class="col-lg-6"><label class="form-label" for="arpa_division_location_id">Vacant ARPA Division *</label><select class="form-select" id="arpa_division_location_id" name="arpa_division_location_id" required><option value="">Select vacant ARPA Division</option><?php foreach($arpaDivisions as $r): ?><option value="<?= e($r['id']) ?>" <?= $selectedDivision===$r['id']?'selected':'' ?>><?= e($r['dad_number'].' - '.$r['name_en']) ?></option><?php endforeach; ?></select><div class="form-text">The shared vacancy rule excludes current and scheduled open appointments.</div></div>
<div class="col-12"><label class="form-label" for="remarks">Remarks</label><textarea class="form-control" id="remarks" name="remarks" rows="3"></textarea></div>
</div></div><button class="btn btn-primary">Create Request</button> <a class="btn btn-outline-secondary" href="<?= e(url('hr/arpa-appointments/new')) ?>">Cancel</a></form>
<?php endif; ?>
