<?php use App\Core\{Csrf,DataTableFormat}; require BASE_PATH.'/app/Views/arpa_appointments/tabs.php'; ?>
<div class="page-heading"><div><div class="breadcrumb-lite">ARPA Officer Assignments / New</div><h1>New ARPA Division Assignment</h1><p>This assignment will be reviewed before it becomes current.</p><?php if($ascDerivedFromContext): ?><div class="text-muted"><strong>Agrarian Service Center:</strong> <?= e((string)$activeAsc['location_name']) ?><?php if(!empty($activeAsc['location_dad_number'])): ?> <span class="ms-1"><?= e((string)$activeAsc['location_dad_number']) ?></span><?php endif; ?></div><?php endif; ?></div></div>
<div class="alert alert-info">An officer must have service permanency recorded and an active Permanent ARPA Division before Acting, Duty Covering, or Attend to the Duty can be requested.</div>
<form id="division-assignment-form" method="post" action="<?= e(url('hr/arpa-appointments/divisions')) ?>" data-options-url="<?= e(url('hr/arpa-appointments/new/options')) ?>" data-initial-issue-key="<?= e($continuityIssue['row_key']??'') ?>" data-initial-review-id="<?= e($continuityIssue['reconciliation_item_id']??'') ?>" data-initial-issues="<?= e(json_encode($unresolvedDataIssues??[],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)) ?>">
<?= Csrf::field() ?>
<div class="form-section"><h2 class="h5">Appointment Request</h2><div class="row g-3">
<?php if(!$ascDerivedFromContext): ?><div class="col-12"><label class="form-label" for="asc_location_id">Agrarian Service Center *</label><select class="form-select" id="asc_location_id" name="asc_location_id" required><option value="">Select Agrarian Service Center</option><?php foreach($ascs as $r): ?><option value="<?= e($r['id']) ?>" <?= $selectedAsc===$r['id']?'selected':'' ?>><?= e($r['dad_number'].' - '.$r['name_en']) ?></option><?php endforeach; ?></select></div><?php endif; ?>
<div class="col-lg-6"><label class="form-label" for="officer_id">Eligible ARPA Officer *</label><select class="form-select" id="officer_id" name="officer_id" required><option value="">Select officer</option><?php foreach($officers as $r): ?><option value="<?= e($r['id']) ?>" data-allowed-types="<?= e(implode(',',(array)($r['allowed_appointment_types']??[]))) ?>" <?= ($selectedOfficer??'')===$r['id']?'selected':'' ?>><?= e($r['dad_number'].' - '.($r['name_with_initials']?:'Unnamed').' ['.DataTableFormat::enumLabel($r['arpa_service_permanency'],'Permanency not set').']') ?></option><?php endforeach; ?></select><div class="form-text">Only active ARPA Officers with a current approved assignment to this Agrarian Service Center Office are available. Appointment rules are evaluated for the selected start date.</div><div id="officer-empty-state" class="text-warning small mt-1" <?= $officers===[]?'':'hidden' ?>>No eligible ARPA Officers are available for <?= e($displayDate??$effectiveDate) ?>.</div></div>
<div class="col-lg-6"><label class="form-label" for="appointment_type">Appointment Type *</label><select class="form-select" id="appointment_type" name="appointment_type" required><option value="">Select an officer first</option><option value="PERMANENT" <?= ($selectedAppointmentType??'')==='PERMANENT'?'selected':'' ?>>Permanent</option><option value="ACTING" <?= ($selectedAppointmentType??'')==='ACTING'?'selected':'' ?>>Acting</option><option value="DUTY_COVERING" <?= ($selectedAppointmentType??'')==='DUTY_COVERING'?'selected':'' ?>>Duty Covering</option><option value="ATTEND_TO_DUTY" <?= ($selectedAppointmentType??'')==='ATTEND_TO_DUTY'?'selected':'' ?>>Attend to the Duty</option></select><div class="form-text" id="appointment-type-help">Appointment types will be shown after you select an officer.</div></div>
<div class="col-lg-6"><label class="form-label" for="effective_from">Appointment Start Date *</label><input class="form-control" id="effective_from" name="effective_from" type="date" value="<?= e($effectiveDate) ?>" required></div>
<div class="col-lg-6"><label class="form-label" for="arpa_division_location_id">ARPA Division / Period to Fill *</label><select class="form-select" id="arpa_division_location_id" name="arpa_division_location_id" required><option value="">Select ARPA Division</option><?php foreach($arpaDivisions as $r): ?><option value="<?= e($r['id']) ?>" data-required-next-start="<?= e($r['required_next_start']??'') ?>" data-last-covered-through="<?= e($r['last_covered_through']??'') ?>" data-continuity-relation="<?= e($r['relation']??'') ?>" data-gap-end="<?= e($r['gap_end']??'') ?>" data-next-existing-start="<?= e($r['next_existing_start']??'') ?>" data-next-existing-end="<?= e($r['next_existing_end']??'') ?>" data-timeline-status="<?= e($r['timeline_status']??'') ?>" <?= ($selectedDivision??'')===$r['id']?'selected':'' ?>><?= e($r['dad_number'].' - '.$r['name_en'].' ['.($r['timeline_label']??'Available').']') ?></option><?php endforeach; ?></select><div class="form-text">Divisions are selected from their complete authoritative timeline since 01 Jan 2025, not current vacancy alone.</div><div id="division-empty-state" class="text-muted small mt-1" <?= $arpaDivisions===[]?'':'hidden' ?>>No ARPA Divisions are available within this Agrarian Service Center on the selected business date.</div></div>
<div class="col-12"><div id="division-continuity" class="border rounded p-3 bg-light" hidden><div class="row g-2"><div class="col-md-3"><span class="text-muted">Historical Coverage</span><div id="historical-coverage" class="fw-semibold">—</div></div><div class="col-md-3"><span class="text-muted">Last Covered Through</span><div id="last-covered-through" class="fw-semibold">—</div></div><div class="col-md-3"><span class="text-muted">Missing Period</span><div id="missing-period" class="fw-semibold">—</div></div><div class="col-md-3"><span class="text-muted">Required Start Date</span><div id="required-next-start" class="fw-semibold">—</div></div><div class="col-md-6 mt-3"><span class="text-muted">Next Existing Assignment</span><div id="next-existing-assignment" class="fw-semibold">—</div></div><div class="col-md-6 mt-3"><span class="text-muted">Maximum End Date</span><div id="maximum-end-date" class="fw-semibold">—</div></div></div><div id="continuity-validation-message" class="alert mt-3 mb-0" hidden></div><a id="continuity-data-issue-link" class="btn btn-sm btn-outline-warning mt-2" data-issue-url="<?= e(url('hr/arpa-appointments/issues/')) ?>" data-review-url="<?= e(url('hr/arpa-appointments/legacy-review/items/')) ?>" href="#" hidden>View Appointment Data Issue</a></div></div>
<div id="bounded-gap-fields" class="col-12" hidden><div class="row g-3"><div class="col-md-4"><label class="form-label" for="effective_to">End Date *</label><input class="form-control" id="effective_to" name="effective_to" type="date" readonly><div class="form-text">Derived as the day before the next authoritative assignment. It cannot be extended or shortened without creating an overlap or another gap.</div></div><div class="col-md-8"><label class="form-label" for="end_reason_id">End Reason *</label><select class="form-select" id="end_reason_id" name="end_reason_id"><option value="">Select the truthful end reason</option><?php foreach($reasons as $r): ?><option value="<?= e($r['id']) ?>"><?= e($r['name_en'].($r['service_terminating']?' (service terminating)':'')) ?></option><?php endforeach; ?></select><div class="form-text">Required for a bounded historical assignment. DEMS does not fabricate an end reason.</div></div></div></div>
<div class="col-12"><div id="appointment-data-issue-panel" class="alert alert-danger" hidden><h2 class="h6">Appointment Data Issue Must Be Resolved First</h2><p id="appointment-data-issue-summary"></p><div id="appointment-data-issue-list" class="small mb-3"></div><a id="appointment-data-issues-review" class="btn btn-sm btn-outline-danger" href="<?= e(url('hr/arpa-appointments/issues?category=HISTORICAL_EXCEPTIONS')) ?>">Review Data Issues</a></div></div>
<div class="col-12"><label class="form-label" for="remarks">Remarks</label><textarea class="form-control" id="remarks" name="remarks" rows="3"></textarea></div>
</div></div>
<div id="eligibility-refresh-message" class="alert alert-secondary mt-3" <?= empty($selectionMessages)?'hidden':'' ?>><?php if(!empty($selectionMessages)): ?><?= e(implode(' ',$selectionMessages)) ?><?php else: ?>Refreshing eligible officers and ARPA Division timelines for the selected date.<?php endif; ?></div>
<div class="mt-3"><button id="submit-division-assignment" class="btn btn-primary" type="submit">Submit</button> <a class="btn btn-outline-secondary" href="<?= e(url('hr/arpa-appointments/submitted')) ?>">Cancel</a></div>
</form>
<script data-cfasync="false" src="<?= e(url('assets/js/arpa-division-form.js')) ?>" defer></script>
