<?php use App\Core\{Csrf,DataTableFormat,SecurityHeaders}; require BASE_PATH.'/app/Views/arpa_appointments/tabs.php'; ?>
<div class="page-heading"><div><div class="breadcrumb-lite">ARPA Officer Assignments / New</div><h1>New ARPA Division Assignment</h1><p>This assignment will be reviewed before it becomes current.</p><?php if($ascDerivedFromContext): ?><div class="text-muted"><strong>Agrarian Service Center:</strong> <?= e((string)$activeAsc['location_name']) ?><?php if(!empty($activeAsc['location_dad_number'])): ?> <span class="ms-1"><?= e((string)$activeAsc['location_dad_number']) ?></span><?php endif; ?></div><?php endif; ?></div></div>
<div class="alert alert-info">An officer must have service permanency recorded and an active Permanent ARPA Division before Acting, Duty Covering, or Attend to the Duty can be requested.</div>
<form id="division-assignment-form" method="post" action="<?= e(url('hr/arpa-appointments/divisions')) ?>" data-refresh-url="<?= e(url('hr/arpa-appointments/new')) ?>">
<?= Csrf::field() ?>
<div class="form-section"><h2 class="h5">Appointment Request</h2><div class="row g-3">
<?php if(!$ascDerivedFromContext): ?><div class="col-12"><label class="form-label" for="asc_location_id">Agrarian Service Center *</label><select class="form-select" id="asc_location_id" name="asc_location_id" required><option value="">Select Agrarian Service Center</option><?php foreach($ascs as $r): ?><option value="<?= e($r['id']) ?>" <?= $selectedAsc===$r['id']?'selected':'' ?>><?= e($r['dad_number'].' - '.$r['name_en']) ?></option><?php endforeach; ?></select></div><?php endif; ?>
<div class="col-lg-6"><label class="form-label" for="officer_id">Eligible ARPA Officer *</label><select class="form-select" id="officer_id" name="officer_id" required><option value="">Select officer</option><?php foreach($officers as $r): ?><option value="<?= e($r['id']) ?>" data-allowed-types="<?= e(implode(',',(array)($r['allowed_appointment_types']??[]))) ?>"><?= e($r['dad_number'].' - '.($r['name_with_initials']?:'Unnamed').' ['.DataTableFormat::enumLabel($r['arpa_service_permanency'],'Permanency not set').']') ?></option><?php endforeach; ?></select><div class="form-text">Only active ARPA Officers with an approved assignment to this Agrarian Service Center are available.</div></div>
<div class="col-lg-6"><label class="form-label" for="appointment_type">Appointment Type *</label><select class="form-select" id="appointment_type" name="appointment_type" required><option value="">Select an officer first</option><option value="PERMANENT">Permanent</option><option value="ACTING">Acting</option><option value="DUTY_COVERING">Duty Covering</option><option value="ATTEND_TO_DUTY">Attend to the Duty</option></select><div class="form-text" id="appointment-type-help">Appointment types will be shown after you select an officer.</div></div>
<div class="col-lg-6"><label class="form-label" for="effective_from">Appointment Start Date *</label><input class="form-control" id="effective_from" name="effective_from" type="date" value="<?= e($effectiveDate) ?>" required></div>
<div class="col-lg-6"><label class="form-label" for="arpa_division_location_id">Vacant ARPA Division *</label><select class="form-select" id="arpa_division_location_id" name="arpa_division_location_id" required><option value="">Select vacant ARPA Division</option><?php foreach($arpaDivisions as $r): ?><option value="<?= e($r['id']) ?>"><?= e($r['dad_number'].' - '.$r['name_en']) ?></option><?php endforeach; ?></select><div class="form-text">Current and scheduled open assignments are not shown.</div></div>
<div class="col-12"><label class="form-label" for="remarks">Remarks</label><textarea class="form-control" id="remarks" name="remarks" rows="3"></textarea></div>
</div></div>
<div id="eligibility-refresh-message" class="alert alert-secondary mt-3" hidden>Refreshing eligible officers and vacant ARPA Divisions for the selected date.</div>
<div class="mt-3"><button id="submit-division-assignment" class="btn btn-primary" type="submit">Submit</button> <a class="btn btn-outline-secondary" href="<?= e(url('hr/arpa-appointments/submitted')) ?>">Cancel</a></div>
</form>
<script nonce="<?= e(SecurityHeaders::nonce()) ?>">(()=>{const form=document.getElementById('division-assignment-form'),date=document.getElementById('effective_from'),asc=document.getElementById('asc_location_id'),officer=document.getElementById('officer_id'),appointmentType=document.getElementById('appointment_type'),typeHelp=document.getElementById('appointment-type-help'),division=document.getElementById('arpa_division_location_id'),submit=document.getElementById('submit-division-assignment'),message=document.getElementById('eligibility-refresh-message');if(!form||!date||!officer||!appointmentType||!division||!submit||!message)return;const applyAppointmentTypes=()=>{const selected=officer.options[officer.selectedIndex],allowed=new Set((selected?.dataset.allowedTypes||'').split(',').filter(Boolean));appointmentType.value='';Array.from(appointmentType.options).forEach((option,index)=>{if(index===0){option.textContent=selected?.value?'Select appointment type':'Select an officer first';return;}const available=allowed.has(option.value);option.hidden=!available;option.disabled=!available;});if(typeHelp)typeHelp.textContent=selected?.value?(allowed.size?'Only appointment types allowed for this officer and date are shown.':'No appointment type is currently available for this officer.'):'Appointment types will be shown after you select an officer.';};const refresh=()=>{officer.value='';division.value='';appointmentType.value='';submit.disabled=true;message.hidden=false;const target=new URL(form.dataset.refreshUrl,window.location.origin);target.searchParams.set('effective_from',date.value);if(asc)target.searchParams.set('asc_location_id',asc.value);window.location.assign(target.toString());};officer.addEventListener('change',applyAppointmentTypes);date.addEventListener('change',refresh);if(asc)asc.addEventListener('change',refresh);applyAppointmentTypes();})();</script>
