<?php use App\Core\{Auth,Csrf,DataTableFormat};
$active=array_values(array_filter($appointments,fn($r)=>$r['current_status']==='ACTIVE'));
$permanent=count(array_filter($active,fn($r)=>$r['appointment_type']==='PERMANENT'));
$acting=count(array_filter($active,fn($r)=>$r['appointment_type']==='ACTING'));
$attend=count(array_filter($active,fn($r)=>$r['appointment_type']==='ATTEND_TO_DUTY'));
$exclusive=count(array_filter($subjects,fn($r)=>$r['current_status']==='ACTIVE' && $r['officer_exclusive_snapshot']));
$invalid=$permanent>1||$acting>1||$attend>1||($exclusive>0&&(count($active)>0||count(array_filter($subjects,fn($r)=>$r['current_status']==='ACTIVE'))>1)); ?>
<div class="page-heading"><div><div class="breadcrumb-lite">ARPA Officer Assignments / Officer Profile</div><h1><?= e($officer['dad_number'].' - '.($officer['name_with_initials']?:$officer['full_name_en'])) ?></h1><p><?= e($officer['designation_name']) ?><?= $officer['class_name']?' / '.e($officer['class_name']):'' ?></p></div></div>
<?php if($invalid): ?><div class="alert alert-danger"><strong>Invalid active combination detected.</strong> Review and close the incompatible historical assignments through controlled workflow.</div><?php endif; ?>
<div class="row g-3 mb-4"><div class="col-lg-6"><div class="form-section h-100"><h2 class="h5">Service Permanency</h2><p><?= DataTableFormat::badge($officer['arpa_service_permanency']?:'NOT SET') ?></p><?php if(Auth::can('arpa.appointment.manage-service')): ?><form method="post" action="<?= e(url('hr/arpa-appointments/officers/'.$officer['id'].'/service-permanency')) ?>"><?= Csrf::field() ?><div class="row g-2"><div class="col-md-5"><select class="form-select" name="service_permanency" required><option value="PERMANENT_IN_SERVICE">Permanent In Service</option><option value="NOT_PERMANENT_IN_SERVICE">Not Permanent In Service</option></select></div><div class="col-md-4"><input class="form-control" type="date" name="effective_from" value="<?= date('Y-m-d') ?>" required></div><div class="col-md-3"><button class="btn btn-outline-primary w-100">Record</button></div><div class="col-12"><input class="form-control" name="reason" placeholder="Reason / reference"></div></div></form><?php endif; ?></div></div><div class="col-lg-6"><div class="form-section h-100"><h2 class="h5">Current Summary</h2><dl class="row mb-0"><dt class="col-7">Permanent Division</dt><dd class="col-5"><?= $permanent ?></dd><dt class="col-7">Acting Division</dt><dd class="col-5"><?= $acting ?></dd><dt class="col-7">Attend to the Duty</dt><dd class="col-5"><?= $attend ?></dd><dt class="col-7">Duty Covering</dt><dd class="col-5"><?= count(array_filter($active,fn($r)=>$r['appointment_type']==='DUTY_COVERING')) ?></dd><dt class="col-7">Exclusive Subjects</dt><dd class="col-5"><?= $exclusive ?></dd></dl></div></div></div>
<?php if(empty($scoped)): ?>
<h2 class="h5 mt-4">Division Appointments — Current and History</h2><?php $dataTable=$divisionHistoryTable;require BASE_PATH.'/app/Views/components/datatable.php'; ?>
<h2 class="h5 mt-4">Subject Assignments — Current and History</h2><?php $dataTable=$subjectHistoryTable;require BASE_PATH.'/app/Views/components/datatable.php'; ?>
<h2 class="h5 mt-4">Service Permanency History</h2><?php $dataTable=$permanencyHistoryTable;require BASE_PATH.'/app/Views/components/datatable.php'; ?>
<h2 class="h5 mt-4">Workflow History</h2><?php $dataTable=$workflowHistoryTable;require BASE_PATH.'/app/Views/components/datatable.php'; ?>
<?php else: ?><div class="alert alert-info mt-4 mb-0">Enterprise-wide employment and workflow history is not included in this scoped operational profile.</div><?php endif; ?>
