<?php use App\Core\Csrf;$type=$request['request_type'];$division=$entity==='division'; ?>
<div class="page-heading"><div><div class="breadcrumb-lite">ARPA Officer Appointments / Returned or Draft Request</div><h1>Edit <?= e(ucwords(strtolower(str_replace('_',' ',$type)))) ?> Request</h1><p>Only the creator can edit a CREATED or RETURNED request. Resubmit it from Pending My Actions.</p></div></div>
<form method="post"><?= Csrf::field() ?><div class="form-section"><div class="row g-3">
<?php if(($division&&$type==='APPOINTMENT')||(!$division&&$type==='ASSIGN')): ?>
<div class="col-md-6"><label class="form-label">ARPA Officer *</label><select class="form-select" name="officer_id" data-searchable-select="Search officers" required><?php foreach($officers as $r): ?><option value="<?= e($r['id']) ?>" <?= $request['officer_id']===$r['id']?'selected':'' ?>><?= e($r['dad_number'].' - '.($r['name_with_initials']?:'Unnamed')) ?></option><?php endforeach; ?></select></div>
<?php endif; ?>
<?php if($division&&$type==='APPOINTMENT'): ?><div class="col-md-3"><label class="form-label">Appointment Type *</label><select class="form-select" name="appointment_type" required><?php foreach(['PERMANENT'=>'Permanent','ACTING'=>'Acting','DUTY_COVERING'=>'Duty Covering','ATTEND_TO_DUTY'=>'Attend to the Duty'] as $v=>$l): ?><option value="<?= $v ?>" <?= $request['appointment_type']===$v?'selected':'' ?>><?= e($l) ?></option><?php endforeach; ?></select></div><?php endif; ?>
<?php if(!$division&&$type==='ASSIGN'): ?><div class="col-md-6"><label class="form-label">ASC *</label><select class="form-select" name="asc_location_id" data-searchable-select="Search ASCs" required><?php foreach($ascs as $r): ?><option value="<?= e($r['id']) ?>" <?= $request['asc_location_id']===$r['id']?'selected':'' ?>><?= e($r['dad_number'].' - '.$r['name_en']) ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">Subject / Function *</label><select class="form-select" name="subject_id" data-searchable-select="Search central subjects" required><?php foreach($subjects as $r): ?><option value="<?= e($r['id']) ?>" <?= $request['subject_id']===$r['id']?'selected':'' ?>><?= e($r['name_en'].' ('.$r['subject_kind'].')') ?></option><?php endforeach; ?></select></div><?php endif; ?>
<?php if($division&&in_array($type,['APPOINTMENT','TRANSFER'],true)): ?><div class="col-md-6"><label class="form-label"><?= $type==='TRANSFER'?'New ':'' ?>ASC *</label><select class="form-select" name="asc_location_id" required><?php foreach($ascs as $r): ?><option value="<?= e($r['id']) ?>" <?= $request['asc_location_id']===$r['id']?'selected':'' ?>><?= e($r['dad_number'].' - '.$r['name_en']) ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label"><?= $type==='TRANSFER'?'New ':'' ?>ARPA Division *</label><select class="form-select" name="arpa_division_location_id" required><?php foreach($arpaDivisions as $r): ?><option value="<?= e($r['id']) ?>" <?= $request['arpa_division_location_id']===$r['id']?'selected':'' ?>><?= e($r['dad_number'].' - '.$r['name_en']) ?></option><?php endforeach; ?></select></div><?php endif; ?>
<?php if(in_array($type,['APPOINTMENT','ASSIGN'],true)): ?><div class="col-md-4"><label class="form-label">Effective From *</label><input class="form-control" type="date" name="effective_from" value="<?= e($request['requested_effective_from']) ?>" required></div><?php endif; ?>
<?php if($type==='TRANSFER'): ?><div class="col-md-3"><label class="form-label">Old Effective To *</label><input class="form-control" type="date" name="old_effective_to" value="<?= e($request['requested_effective_to']) ?>" required></div><div class="col-md-3"><label class="form-label">New Effective From *</label><input class="form-control" type="date" name="new_effective_from" value="<?= e($request['requested_effective_from']) ?>" required></div><?php endif; ?>
<?php if($type==='END'): ?><div class="col-md-4"><label class="form-label">Effective To *</label><input class="form-control" type="date" name="effective_to" value="<?= e($request['requested_effective_to']) ?>" required></div><?php endif; ?>
<?php if(in_array($type,['END','TRANSFER'],true)): ?><div class="col-md-8"><label class="form-label">End Reason *</label><select class="form-select" name="end_reason_id" required><?php foreach($reasons as $r): ?><option value="<?= e($r['id']) ?>" <?= $request['end_reason_id']===$r['id']?'selected':'' ?>><?= e($r['name_en']) ?></option><?php endforeach; ?></select></div><?php endif; ?>
<div class="col-12"><label class="form-label">Remarks</label><textarea class="form-control" name="remarks" rows="3"><?= e($request['request_remarks']) ?></textarea></div>
</div></div><button class="btn btn-primary">Save Corrections</button> <a class="btn btn-outline-secondary" href="<?= e(url('hr/arpa-appointments/pending')) ?>">Cancel</a></form>
