<?php use App\Core\Csrf; ?>
<div class="page-heading"><div><div class="breadcrumb-lite">ARPA Officer Assignments / Subjects / New</div><h1>New ASC Subject Assignment</h1><p>Assign an approved subject or function at the Agrarian Service Center.</p></div></div>
<div class="alert alert-warning"><strong>Exclusive officer rule:</strong> Agrarian Bank, Sales Shop, and Sithamu cannot overlap any other assignment held by the same officer. Existing records must be closed explicitly.</div>
<form method="post" action="<?= e(url('hr/arpa-appointments/subjects')) ?>"><?= Csrf::field() ?><div class="form-section"><h2 class="h5">Assignment request</h2><div class="row g-3">
<div class="col-lg-4"><label class="form-label">ARPA Officer *</label><select class="form-select" name="officer_id" data-searchable-select="Search officers" required><option value="">Select officer</option><?php foreach($officers as $r): ?><option value="<?= e($r['id']) ?>"><?= e($r['dad_number'].' - '.($r['name_with_initials']?:'Unnamed')) ?></option><?php endforeach; ?></select></div>
<div class="col-lg-4"><label class="form-label">ASC *</label><select class="form-select" name="asc_location_id" data-searchable-select="Search ASCs" required><option value="">Select ASC</option><?php foreach($ascs as $r): ?><option value="<?= e($r['id']) ?>"><?= e($r['dad_number'].' - '.$r['name_en']) ?></option><?php endforeach; ?></select></div>
<div class="col-lg-4"><label class="form-label">Subject / Function *</label><select class="form-select" name="subject_id" data-searchable-select="Search central subjects" required><option value="">Select subject</option><?php foreach($subjects as $r): ?><option value="<?= e($r['id']) ?>"><?= e($r['name_en'].' ('.$r['subject_kind'].')') ?></option><?php endforeach; ?></select><div class="form-text">Subjects are defined centrally by Head Office and are available to every ASC.</div></div>
<div class="col-md-4"><label class="form-label">Start Date *</label><input class="form-control" type="date" name="effective_from" value="<?= date('Y-m-d') ?>" required></div><div class="col-md-8"><label class="form-label">Remarks</label><input class="form-control" name="remarks"></div>
</div></div><button class="btn btn-primary">Submit</button> <a class="btn btn-outline-secondary" href="<?= e(url('hr/arpa-appointments/subjects')) ?>">Cancel</a></form>
