<?php use App\Core\Csrf;$editing=is_array($subject); ?>
<div class="page-heading"><div><div class="breadcrumb-lite">Subject Management / Head Office</div><h1><?= $editing?'Edit':'Add' ?> Central Subject</h1><p>This master is global. ASC context is selected only when assigning an officer.</p></div></div>
<form method="post" action="<?= e(url($editing?'subjects/'.$subject['id'].'/edit':'subjects')) ?>"><?= Csrf::field() ?><div class="form-section"><div class="row g-3">
<div class="col-md-4"><label class="form-label">System Key *</label><input class="form-control" name="system_key" value="<?= e($subject['system_key']??'') ?>" pattern="[A-Z][A-Z0-9_]{1,99}" <?= $editing?'readonly':'' ?> required><div class="form-text">Stable technical key; it cannot be renamed after creation.</div></div>
<div class="col-md-4"><label class="form-label">English Name *</label><input class="form-control" name="name_en" value="<?= e($subject['name_en']??'') ?>" required></div>
<div class="col-md-4"><label class="form-label">Subject Kind *</label><select class="form-select" name="subject_kind" required><?php foreach(['NORMAL'=>'Normal','AGRARIAN_BANK'=>'Agrarian Bank','SALES_SHOP'=>'Sales Shop','SITHAMU'=>'Sithamu'] as $v=>$l): ?><option value="<?= $v ?>" <?= ($subject['subject_kind']??'NORMAL')===$v?'selected':'' ?>><?= e($l) ?></option><?php endforeach; ?></select></div>
<div class="col-md-6"><label class="form-label">Sinhala Name</label><input class="form-control" name="name_si" value="<?= e($subject['name_si']??'') ?>"></div><div class="col-md-6"><label class="form-label">Tamil Name</label><input class="form-control" name="name_ta" value="<?= e($subject['name_ta']??'') ?>"></div>
<?php if($editing): ?><div class="col-md-4"><label class="form-label">Status</label><select class="form-select" name="active"><option value="1" <?= $subject['active']?'selected':'' ?>>Active</option><option value="0" <?= !$subject['active']?'selected':'' ?>>Inactive</option></select></div><?php endif; ?>
</div></div><button class="btn btn-primary"><?= $editing?'Save Changes':'Create Subject' ?></button> <a class="btn btn-outline-secondary" href="<?= e(url('subjects')) ?>">Cancel</a></form>
