<?php use App\Core\{Auth,Csrf}; ?>
<div class="page-heading"><div><div class="breadcrumb-lite">Human Resource Management / <?= e($cfg['label']) ?></div><h1>Officer Supporting Masters</h1><p>Maintain Title, Appointment Nature, Designation, Class, Officer Status and Civil Status reference data.</p></div><?php if(Auth::can('hr.master.create')): ?><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addMaster"><i class="bi bi-plus-lg"></i> Add <?= e($cfg['label']) ?></button><?php endif; ?></div>
<ul class="nav nav-tabs mb-3">
<?php $tabs=['titles'=>'Title','appointment-natures'=>'Appointment Nature','designations'=>'Designation','classes'=>'Class','officer-statuses'=>'Officer Status','civil-statuses'=>'Civil Status']; foreach($tabs as $key=>$label): ?><li class="nav-item"><a class="nav-link <?= $type===$key?'active':'' ?>" href="<?= e(url('hr/'.$key)) ?>"><?= e($label) ?></a></li><?php endforeach; ?>
</ul>
<?php require BASE_PATH . '/app/Views/components/datatable.php'; ?>
<?php if(Auth::can('hr.master.create')): ?><div class="modal fade" id="addMaster" tabindex="-1"><div class="modal-dialog modal-lg"><form method="post" action="<?= e(url('hr/'.$type)) ?>" class="modal-content"><?= Csrf::field() ?><div class="modal-header"><h5 class="modal-title">Add <?= e($cfg['label']) ?></h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">English Name *</label><input class="form-control" name="name_en" required></div><div class="col-md-3"><label class="form-label">Display Order</label><input type="number" class="form-control" name="display_order" value="100"></div><div class="col-md-3"><label class="form-label">Effective From</label><input type="date" class="form-control" name="effective_from" value="<?= date('Y-m-d') ?>"></div><div class="col-md-6"><label class="form-label">Sinhala Name</label><input class="form-control" name="name_si"></div><div class="col-md-6"><label class="form-label">Tamil Name</label><input class="form-control" name="name_ta"></div>
<?php if($type==='appointment-natures'): ?><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="class_required" id="classRequired"><label class="form-check-label" for="classRequired">Class Required</label></div></div><?php endif; ?>
<?php if($type==='designations'): ?><div class="col-md-4"><label class="form-label">Designation Level</label><select class="form-select" name="designation_level"><option>MAIN</option><option>SUB</option></select></div><?php endif; ?>
<div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="description" rows="2"></textarea></div></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Save Draft</button></div></form></div></div><?php endif; ?>
