<?php
use App\Core\Csrf;
$isEdit=isset($location);
$hierarchyParents=[
    'district_location_id'=>'province_location_id',
    'ds_division_location_id'=>'district_location_id',
    'asc_location_id'=>'district_location_id',
    'arpa_division_location_id'=>'asc_location_id',
];
?>
<div class="page-heading"><div><div class="breadcrumb-lite">Organization / Locations / <?= $isEdit?'Edit':'Add' ?></div><h1><?= $isEdit?'Edit Location':'Add Location' ?></h1></div></div>
<form method="post" action="<?= e(url($isEdit?'locations/'.$location['id'].'/edit':'locations')) ?>"><?= Csrf::field() ?><div class="form-section"><div class="row g-3">
<?php if($isEdit): ?><div class="col-md-4"><label class="form-label">DAD Number</label><input class="form-control" value="<?= e($location['dad_number']) ?>" readonly></div><div class="col-md-4"><label class="form-label">Location Type</label><input class="form-control" value="<?= e($location['type_name']) ?>" readonly data-current-location-type="<?= e($location['type_key']) ?>"></div><?php else: ?><div class="col-md-4"><label class="form-label">Location Type *</label><select class="form-select" name="location_type_id" required><option value="">Select</option><?php foreach($types as $r): ?><option value="<?= e($r['id']) ?>" data-system-key="<?= e($r['system_key']) ?>"><?= e($r['name_en']) ?></option><?php endforeach; ?></select></div><?php endif; ?>
<div class="col-md-4"><label class="form-label">Official Code</label><input class="form-control" name="official_code" value="<?= e($location['official_code']??'') ?>"></div><div class="col-md-4"><label class="form-label">Start Date *</label><input type="date" class="form-control" name="effective_from" value="<?= e($location['effective_from']??date('Y-m-d')) ?>" required></div>
<div class="col-md-4" data-gn-identifier><label class="form-label">GN Code</label><input class="form-control" name="gn_code" maxlength="20" value="<?= e($location['gn_code']??'') ?>"></div><div class="col-md-4" data-gn-identifier><label class="form-label">GN Code for PLR</label><input class="form-control" name="gn_code_for_plr" maxlength="11" value="<?= e($location['gn_code_for_plr']??'') ?>"></div>
<div class="col-md-4"><label class="form-label">English Name *</label><input class="form-control" name="name_en" value="<?= e($location['name_en']??'') ?>" required></div><div class="col-md-4"><label class="form-label">Sinhala Name</label><input class="form-control" name="name_si" value="<?= e($location['name_si']??'') ?>"></div><div class="col-md-4"><label class="form-label">Tamil Name</label><input class="form-control" name="name_ta" value="<?= e($location['name_ta']??'') ?>"></div>
</div></div><?php if($isEdit&&($hierarchy['fields']??[])!==[]): ?><div class="form-section" data-location-cascade data-endpoint="<?= e(url('locations/hierarchy-options')) ?>"><h5>Location Structure</h5><div class="row g-3"><?php foreach($hierarchy['fields'] as [$field,$label,$optionType,$required]): $selected=(string)($hierarchy['values'][$field]??''); ?><div class="col-md-6"><label class="form-label"><?= e($label) ?><?= $required?' *':'' ?></label><select class="form-select" name="<?= e($field) ?>" data-location-type="<?= e($optionType) ?>" data-initial-value="<?= e($selected) ?>"<?= isset($hierarchyParents[$field])?' data-parent-field="'.e($hierarchyParents[$field]).'"':'' ?><?= $required?' required':'' ?>><option value=""><?= $required?'Select':'Not linked' ?></option><?php foreach($hierarchy['options'][$optionType]??[] as $option): ?><option value="<?= e($option['id']) ?>"<?= $selected===(string)$option['id']?' selected':'' ?>><?= e($option['dad_number'].' - '.$option['name_en']) ?></option><?php endforeach; ?></select></div><?php endforeach; ?></div></div><?php endif; ?><?php if($isEdit): ?><div class="alert alert-info">This SYSTEM_ADMIN change is saved directly. Superseded hierarchy relationships are ended and approved replacements become effective immediately. The DAD number, Location Type, status, and approval state remain unchanged.</div><?php endif; ?><button class="btn btn-primary"><?= $isEdit?'Save Changes':'Submit' ?></button> <a class="btn btn-outline-secondary" href="<?= e(url($isEdit?'locations/'.$location['id']:'locations')) ?>">Cancel</a></form>
<script data-cfasync="false" src="<?= e(url('assets/js/location-hierarchy-cascade.js')) ?>" defer></script>
